$ErrorActionPreference = "Stop"

$repo = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
Write-Host ("[DIAG] Repo: " + $repo)

. (Join-Path $PSScriptRoot "_bootstrap.ps1")

$changed = New-Object System.Collections.Generic.List[string]

function WriteFileLines([string]$rel, [string[]]$lines) {
  $full = Join-Path $repo $rel
  EnsureDir (Split-Path -Parent $full) | Out-Null
  $bk = $null
  if (Test-Path -LiteralPath $full) { $bk = BackupFile $full }
  $content = $lines -join "`r`n"
  WriteUtf8NoBom $full $content
  Write-Host ("[OK] wrote: " + $full)
  if ($bk) { Write-Host ("[BK] " + $bk) }
  $script:changed.Add($full) | Out-Null
}

# 1) Component: TrilhasV2
$compLines = @(
'import Link from "next/link";',
'import React from "react";',
'',
'export type TrailStep = { id?: string; title?: string; href?: string; kind?: string };',
'export type Trail = { id: string; title: string; summary?: string; steps?: TrailStep[] };',
'',
'function countSteps(t: Trail): number {',
'  return Array.isArray(t.steps) ? t.steps.length : 0;',
'}',
'',
'export function TrilhasV2(props: { slug: string; title: string; trails: Trail[] }) {',
'  const trails = Array.isArray(props.trails) ? props.trails : [];',
'',
'  return (',
'    <div style={{ display: "grid", gap: 12 }}>',
'      <header',
'        style={{',
'          border: "1px solid rgba(255,255,255,0.10)",',
'          borderRadius: 14,',
'          padding: 12,',
'          background: "rgba(0,0,0,0.22)",',
'          display: "flex",',
'          alignItems: "center",',
'          justifyContent: "space-between",',
'          gap: 12,',
'          flexWrap: "wrap",',
'        }}',
'      >',
'        <div style={{ display: "flex", flexDirection: "column", gap: 2 }}>',
'          <div style={{ fontSize: 12, opacity: 0.75 }}>Trilhas V2</div>',
'          <div style={{ fontSize: 16, fontWeight: 900 }}>{props.title}</div>',
'        </div>',
'        <div',
'          style={{',
'            fontSize: 12,',
'            opacity: 0.9,',
'            padding: "6px 10px",',
'            borderRadius: 999,',
'            border: "1px solid rgba(255,255,255,0.12)",',
'          }}',
'        >',
'          {trails.length} trilha(s)',
'        </div>',
'      </header>',
'',
'      {trails.length ? (',
'        <div style={{ display: "grid", gap: 10 }}>',
'          {trails.map((t) => {',
'            const steps = countSteps(t);',
'            const href = "/c/" + props.slug + "/v2/trilhas/" + encodeURIComponent(t.id);',
'            return (',
'              <section',
'                key={t.id}',
'                style={{',
'                  borderRadius: 14,',
'                  padding: 12,',
'                  border: "1px solid rgba(255,255,255,0.10)",',
'                  background: "rgba(0,0,0,0.18)",',
'                  display: "grid",',
'                  gap: 10,',
'                }}',
'              >',
'                <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12, flexWrap: "wrap" }}>',
'                  <div style={{ display: "grid", gap: 6, minWidth: 260 }}>',
'                    <div style={{ fontSize: 14, fontWeight: 950 }}>{t.title}</div>',
'                    {t.summary ? (',
'                      <div style={{ fontSize: 13, lineHeight: 1.45, opacity: 0.95 }}>{t.summary}</div>',
'                    ) : null}',
'                    <div style={{ fontSize: 12, opacity: 0.75 }}>id: {t.id}</div>',
'                  </div>',
'',
'                  <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>',
'                    <span',
'                      style={{',
'                        fontSize: 12,',
'                        opacity: 0.9,',
'                        padding: "6px 10px",',
'                        borderRadius: 999,',
'                        border: "1px solid rgba(255,255,255,0.12)",',
'                      }}',
'                    >',
'                      {steps} etapa(s)',
'                    </span>',
'                    <Link',
'                      href={href}',
'                      style={{',
'                        display: "inline-flex",',
'                        alignItems: "center",',
'                        justifyContent: "center",',
'                        gap: 8,',
'                        fontSize: 12,',
'                        fontWeight: 900,',
'                        padding: "10px 12px",',
'                        borderRadius: 12,',
'                        textDecoration: "none",',
'                        color: "#111",',
'                        background: "var(--accent)",',
'                        border: "1px solid rgba(0,0,0,0.35)",',
'                      }}',
'                      title="Abrir trilha"',
'                    >',
'                      Abrir',
'                    </Link>',
'                  </div>',
'                </div>',
'              </section>',
'            );',
'          })}',
'        </div>',
'      ) : (',
'        <div',
'          style={{',
'            borderRadius: 14,',
'            padding: 12,',
'            border: "1px solid rgba(255,255,255,0.10)",',
'            background: "rgba(0,0,0,0.18)",',
'            fontSize: 13,',
'            lineHeight: 1.55,',
'            opacity: 0.95,',
'          }}',
'        >',
'          Nenhuma trilha ainda. Você pode criar um arquivo <b>trilhas.json</b> dentro do caderno ou adicionar nodes no mapa com <b>type: "trail"</b>.',
'        </div>',
'      )}',
'',
'      <footer',
'        style={{',
'          borderRadius: 14,',
'          padding: 12,',
'          border: "1px solid rgba(255,255,255,0.10)",',
'          background: "rgba(0,0,0,0.14)",',
'          fontSize: 12,',
'          opacity: 0.9,',
'          lineHeight: 1.6,',
'        }}',
'      >',
'        <div style={{ fontWeight: 900, marginBottom: 6 }}>Formato sugerido (trilhas.json)</div>',
'        <div style={{ opacity: 0.85 }}>',
'          Top-level pode ser array de trilhas. Cada trilha: id, title, summary opcional, steps opcional (id/title/href).',
'        </div>',
'      </footer>',
'    </div>',
'  );',
'}'
)
WriteFileLines "src\components\v2\TrilhasV2.tsx" $compLines

# 2) Page: /c/[slug]/v2/trilhas
$pageList = @(
'import { notFound } from "next/navigation";',
'import type { CSSProperties } from "react";',
'import { readFile } from "node:fs/promises";',
'import { join } from "node:path";',
'import { getCaderno } from "@/lib/cadernos";',
'import V2Nav from "@/components/v2/V2Nav";',
'import { TrilhasV2, type Trail, type TrailStep } from "@/components/v2/TrilhasV2";',
'',
'type AccentStyle = CSSProperties & Record<"--accent", string>;',
'type AnyObj = Record<string, unknown>;',
'',
'function isObj(v: unknown): v is AnyObj {',
'  return !!v && typeof v === "object" && !Array.isArray(v);',
'}',
'',
'function asStr(v: unknown): string {',
'  return typeof v === "string" ? v : "";',
'}',
'',
'function trailFromUnknown(v: unknown, idx: number): Trail | null {',
'  if (!isObj(v)) return null;',
'  const id = asStr(v["id"]) || ("trilha-" + String(idx + 1));',
'  const title = asStr(v["title"]) || id;',
'  const summary = asStr(v["summary"]) || asStr(v["desc"]) || "";',
'  const rawSteps = v["steps"];',
'  const steps: TrailStep[] = Array.isArray(rawSteps)',
'    ? rawSteps.map((s, j) => {',
'        if (!isObj(s)) return { id: "etapa-" + String(j + 1), title: "Etapa " + String(j + 1) };',
'        return {',
'          id: asStr(s["id"]) || ("etapa-" + String(j + 1)),',
'          title: asStr(s["title"]) || asStr(s["label"]) || ("Etapa " + String(j + 1)),',
'          href: asStr(s["href"]) || asStr(s["url"]) || "",',
'          kind: asStr(s["kind"]) || asStr(s["type"]) || "",',
'        };',
'      })',
'    : [];',
'  return { id, title, summary: summary || undefined, steps: steps.length ? steps : undefined };',
'}',
'',
'function trailsFromMapa(mapa: unknown): Trail[] {',
'  if (!mapa) return [];',
'  const nodes: unknown[] = Array.isArray(mapa)',
'    ? mapa',
'    : isObj(mapa) && Array.isArray(mapa["nodes"])',
'      ? (mapa["nodes"] as unknown[])',
'      : isObj(mapa) && Array.isArray(mapa["items"])',
'        ? (mapa["items"] as unknown[])',
'        : [];',
'',
'  const out: Trail[] = [];',
'  for (let i = 0; i < nodes.length; i++) {',
'    const n = nodes[i];',
'    if (!isObj(n)) continue;',
'    const t = asStr(n["type"]) || asStr(n["kind"]);',
'    if (t !== "trail") continue;',
'    const id = asStr(n["id"]) || ("trail-" + String(i + 1));',
'    const title = asStr(n["title"]) || asStr(n["label"]) || id;',
'    const summary = asStr(n["summary"]) || asStr(n["desc"]) || "";',
'    const rawSteps = n["steps"];',
'    const steps: TrailStep[] = Array.isArray(rawSteps)',
'      ? rawSteps.map((s, j) => {',
'          if (!isObj(s)) return { id: "etapa-" + String(j + 1), title: "Etapa " + String(j + 1) };',
'          return {',
'            id: asStr(s["id"]) || ("etapa-" + String(j + 1)),',
'            title: asStr(s["title"]) || asStr(s["label"]) || ("Etapa " + String(j + 1)),',
'            href: asStr(s["href"]) || asStr(s["url"]) || "",',
'            kind: asStr(s["kind"]) || asStr(s["type"]) || "",',
'          };',
'        })',
'      : [];',
'    out.push({ id, title, summary: summary || undefined, steps: steps.length ? steps : undefined });',
'  }',
'  return out;',
'}',
'',
'async function loadTrilhasJson(slug: string): Promise<unknown | null> {',
'  try {',
'    const p = join(process.cwd(), "content", "cadernos", slug, "trilhas.json");',
'    const raw = await readFile(p, "utf8");',
'    return JSON.parse(raw) as unknown;',
'  } catch {',
'    return null;',
'  }',
'}',
'',
'function trailsFromJson(v: unknown): Trail[] {',
'  const arr: unknown[] = Array.isArray(v)',
'    ? v',
'    : isObj(v) && Array.isArray(v["trilhas"])',
'      ? (v["trilhas"] as unknown[])',
'      : [];',
'',
'  const out: Trail[] = [];',
'  for (let i = 0; i < arr.length; i++) {',
'    const t = trailFromUnknown(arr[i], i);',
'    if (t && t.id && t.title) out.push(t);',
'  }',
'  return out;',
'}',
'',
'export default async function Page({ params }: { params: Promise<{ slug: string }> }) {',
'  const { slug } = await params;',
'',
'  let data: Awaited<ReturnType<typeof getCaderno>>;',
'  try {',
'    data = await getCaderno(slug);',
'  } catch (e) {',
'    const err = e as { code?: string };',
'    if (err && err.code === "ENOENT") return notFound();',
'    throw e;',
'  }',
'',
'  const title = data.meta?.title ?? slug;',
'  const accent = data.meta?.accent ?? "#F7C600";',
'  const s: AccentStyle = { ["--accent"]: accent } as AccentStyle;',
'',
'  const json = await loadTrilhasJson(slug);',
'  const fromJson = trailsFromJson(json);',
'  const fromMapa = trailsFromMapa((data as unknown as AnyObj)["mapa"]);',
'  const trails = fromJson.length ? fromJson : fromMapa;',
'',
'  return (',
'    <main style={{ padding: 14, maxWidth: 1100, margin: "0 auto", ...s }}>',
'      <V2Nav slug={slug} active="trilhas" />',
'      <div style={{ marginTop: 12 }}>',
'        <TrilhasV2 slug={slug} title={title} trails={trails} />',
'      </div>',
'    </main>',
'  );',
'}'
)
WriteFileLines "src\app\c\[slug]\v2\trilhas\page.tsx" $pageList

# 3) Page: /c/[slug]/v2/trilhas/[id]
$pageDetail = @(
'import { notFound } from "next/navigation";',
'import type { CSSProperties } from "react";',
'import Link from "next/link";',
'import { readFile } from "node:fs/promises";',
'import { join } from "node:path";',
'import { getCaderno } from "@/lib/cadernos";',
'import V2Nav from "@/components/v2/V2Nav";',
'import type { Trail, TrailStep } from "@/components/v2/TrilhasV2";',
'',
'type AccentStyle = CSSProperties & Record<"--accent", string>;',
'type AnyObj = Record<string, unknown>;',
'',
'function isObj(v: unknown): v is AnyObj {',
'  return !!v && typeof v === "object" && !Array.isArray(v);',
'}',
'',
'function asStr(v: unknown): string {',
'  return typeof v === "string" ? v : "";',
'}',
'',
'function trailFromUnknown(v: unknown, idx: number): Trail | null {',
'  if (!isObj(v)) return null;',
'  const id = asStr(v["id"]) || ("trilha-" + String(idx + 1));',
'  const title = asStr(v["title"]) || id;',
'  const summary = asStr(v["summary"]) || asStr(v["desc"]) || "";',
'  const rawSteps = v["steps"];',
'  const steps: TrailStep[] = Array.isArray(rawSteps)',
'    ? rawSteps.map((s, j) => {',
'        if (!isObj(s)) return { id: "etapa-" + String(j + 1), title: "Etapa " + String(j + 1) };',
'        return {',
'          id: asStr(s["id"]) || ("etapa-" + String(j + 1)),',
'          title: asStr(s["title"]) || asStr(s["label"]) || ("Etapa " + String(j + 1)),',
'          href: asStr(s["href"]) || asStr(s["url"]) || "",',
'          kind: asStr(s["kind"]) || asStr(s["type"]) || "",',
'        };',
'      })',
'    : [];',
'  return { id, title, summary: summary || undefined, steps: steps.length ? steps : undefined };',
'}',
'',
'async function loadTrilhasJson(slug: string): Promise<unknown | null> {',
'  try {',
'    const p = join(process.cwd(), "content", "cadernos", slug, "trilhas.json");',
'    const raw = await readFile(p, "utf8");',
'    return JSON.parse(raw) as unknown;',
'  } catch {',
'    return null;',
'  }',
'}',
'',
'function trailsFromJson(v: unknown): Trail[] {',
'  const arr: unknown[] = Array.isArray(v)',
'    ? v',
'    : isObj(v) && Array.isArray(v["trilhas"])',
'      ? (v["trilhas"] as unknown[])',
'      : [];',
'  const out: Trail[] = [];',
'  for (let i = 0; i < arr.length; i++) {',
'    const t = trailFromUnknown(arr[i], i);',
'    if (t && t.id && t.title) out.push(t);',
'  }',
'  return out;',
'}',
'',
'export default async function Page({ params }: { params: Promise<{ slug: string; id: string }> }) {',
'  const { slug, id } = await params;',
'  const wanted = decodeURIComponent(id);',
'',
'  let data: Awaited<ReturnType<typeof getCaderno>>;',
'  try {',
'    data = await getCaderno(slug);',
'  } catch (e) {',
'    const err = e as { code?: string };',
'    if (err && err.code === "ENOENT") return notFound();',
'    throw e;',
'  }',
'',
'  const title = data.meta?.title ?? slug;',
'  const accent = data.meta?.accent ?? "#F7C600";',
'  const s: AccentStyle = { ["--accent"]: accent } as AccentStyle;',
'',
'  const json = await loadTrilhasJson(slug);',
'  const trails = trailsFromJson(json);',
'  const trail = trails.find((t) => t.id === wanted) ?? null;',
'  if (!trail) return notFound();',
'',
'  const back = "/c/" + slug + "/v2/trilhas";',
'',
'  return (',
'    <main style={{ padding: 14, maxWidth: 1100, margin: "0 auto", ...s }}>',
'      <V2Nav slug={slug} active="trilhas" />',
'',
'      <div style={{ marginTop: 12, display: "grid", gap: 12 }}>',
'        <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>',
'          <Link href={back} style={{ fontSize: 12, fontWeight: 900, textDecoration: "none", opacity: 0.95 }}>',
'            ← Voltar para Trilhas',
'          </Link>',
'          <span style={{ fontSize: 12, opacity: 0.75 }}>id: {trail.id}</span>',
'        </div>',
'',
'        <header',
'          style={{',
'            border: "1px solid rgba(255,255,255,0.10)",',
'            borderRadius: 14,',
'            padding: 12,',
'            background: "rgba(0,0,0,0.22)",',
'            display: "grid",',
'            gap: 6,',
'          }}',
'        >',
'          <div style={{ fontSize: 12, opacity: 0.75 }}>Trilha</div>',
'          <div style={{ fontSize: 18, fontWeight: 950 }}>{trail.title}</div>',
'          {trail.summary ? <div style={{ fontSize: 13, lineHeight: 1.55, opacity: 0.95 }}>{trail.summary}</div> : null}',
'        </header>',
'',
'        <section',
'          style={{',
'            borderRadius: 14,',
'            padding: 12,',
'            border: "1px solid rgba(255,255,255,0.10)",',
'            background: "rgba(0,0,0,0.18)",',
'            display: "grid",',
'            gap: 10,',
'          }}',
'        >',
'          <div style={{ fontSize: 13, fontWeight: 900 }}>Etapas</div>',
'          {Array.isArray(trail.steps) && trail.steps.length ? (',
'            <ol style={{ margin: 0, paddingLeft: 18, display: "grid", gap: 8 }}>',
'              {trail.steps.map((st, idx) => {',
'                const label = st.title || ("Etapa " + String(idx + 1));',
'                const href = st.href || "";',
'                return (',
'                  <li key={(st.id || "etapa") + "-" + String(idx)} style={{ lineHeight: 1.45 }}>',
'                    {href ? (',
'                      <a href={href} style={{ color: "var(--accent)", fontWeight: 900, textDecoration: "none" }}>',
'                        {label}',
'                      </a>',
'                    ) : (',
'                      <span style={{ fontWeight: 800 }}>{label}</span>',
'                    )}',
'                    {st.kind ? <span style={{ marginLeft: 8, fontSize: 12, opacity: 0.75 }}>({st.kind})</span> : null}',
'                  </li>',
'                );',
'              })}',
'            </ol>',
'          ) : (',
'            <div style={{ fontSize: 13, opacity: 0.9 }}>',
'              Esta trilha ainda nao tem steps. Edite trilhas.json e adicione um array steps.',
'            </div>',
'          )}',
'        </section>',
'',
'        <div style={{ fontSize: 12, opacity: 0.85 }}>',
'          Dica: steps podem apontar para V2 (mapa, debate, provas, linha do tempo) usando href.',
'        </div>',
'      </div>',
'    </main>',
'  );',
'}'
)
WriteFileLines "src\app\c\[slug]\v2\trilhas\[id]\page.tsx" $pageDetail

# VERIFY
$verify = Join-Path $repo "tools\cv-verify.ps1"
Write-Host ("[RUN] " + $verify)
RunPs1 $verify

# REPORT
$rep = New-Object System.Collections.Generic.List[string]
$rep.Add("# CV — Step D6 — Trilhas V2 (v0_74)") | Out-Null
$rep.Add("") | Out-Null
$rep.Add("## O que entrou") | Out-Null
$rep.Add("- Componente TrilhasV2 (lista de trilhas).") | Out-Null
$rep.Add("- Pagina /c/[slug]/v2/trilhas (carrega trilhas.json opcional; fallback via mapa type trail).") | Out-Null
$rep.Add("- Pagina /c/[slug]/v2/trilhas/[id] (detalhe; steps com href opcional).") | Out-Null
$rep.Add("") | Out-Null
$rep.Add("## Arquivos alterados") | Out-Null
foreach ($f in $changed) { $rep.Add("- " + $f) | Out-Null }
$rep.Add("") | Out-Null
$rep.Add("## Verify") | Out-Null
$rep.Add("- tools/cv-verify.ps1 (guard + lint + build)") | Out-Null

$rp = WriteReport "cv-step-d6-trilhasv2-v0_74.md" ($rep -join "`n")
Write-Host ("[OK] Report: " + $rp)
Write-Host "[OK] Step D6 aplicado e verificado."