param(
  [switch]$SkipBuild
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function WL([string]$s) { Write-Host $s }
function EnsureDir([string]$p) { if (-not (Test-Path -LiteralPath $p)) { New-Item -ItemType Directory -Force -Path $p | Out-Null } }
function WriteUtf8NoBom([string]$p, [string]$content) {
  $parent = Split-Path -Parent $p
  if ($parent) { EnsureDir $parent }
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($p, $content, $enc)
}
function BackupFile([string]$p) {
  if (Test-Path -LiteralPath $p) {
    $ts = (Get-Date -Format "yyyyMMdd_HHmmss")
    $bakDir = Join-Path (Get-Location) "tools\_patch_backup"
    EnsureDir $bakDir
    $leaf = Split-Path -Leaf $p
    Copy-Item -LiteralPath $p -Destination (Join-Path $bakDir ($leaf + "." + $ts + ".bak")) -Force
  }
}
function ResolveExe([string]$name) {
  $cmd = Get-Command $name -ErrorAction SilentlyContinue
  if ($cmd -and $cmd.Source) { return $cmd.Source }
  return $name
}
function RunNative([string]$cwd, [string]$exe, [string[]]$cmdArgs) {
  $pretty = ($cmdArgs -join " ")
  WL ("[RUN] " + $exe + " " + $pretty)
  Push-Location $cwd
  & $exe @cmdArgs
  $code = $LASTEXITCODE
  Pop-Location
  if ($code -ne 0) { throw ("[STOP] comando falhou (exit " + $code + "): " + $exe + " " + $pretty) }
}
function ResolveRepoHere() {
  $here = (Get-Location).Path
  if (Test-Path -LiteralPath (Join-Path $here "package.json")) { return $here }
  $p1 = Split-Path -Parent $here
  if ($p1 -and (Test-Path -LiteralPath (Join-Path $p1 "package.json"))) { return $p1 }
  throw ("[STOP] Rode na raiz do repo (onde tem package.json). Atual: " + $here)
}

# -------------------------
# DIAG
# -------------------------
$repo = ResolveRepoHere
$npmExe = ResolveExe "npm.cmd"
$mapComp = Join-Path $repo "src\components\TerritoryMap.tsx"

WL ("[DIAG] Repo: " + $repo)
WL ("[DIAG] npm: " + $npmExe)
WL ("[DIAG] TerritoryMap: " + $mapComp)

if (-not (Test-Path -LiteralPath $mapComp)) { throw ("[STOP] Não achei: " + $mapComp) }

# -------------------------
# PATCH
# -------------------------
BackupFile $mapComp

$lines = @()

$lines += '"use client";'
$lines += ''
$lines += 'import { useMemo, useState } from "react";'
$lines += 'import { useParams } from "next/navigation";'
$lines += ''
$lines += 'export type MapPointKind ='
$lines += '  | "ponto-critico"'
$lines += '  | "mutirao"'
$lines += '  | "instituicao"'
$lines += '  | "ponto-eco"'
$lines += '  | "outro";'
$lines += ''
$lines += 'export type MapPoint = {'
$lines += '  id: string;'
$lines += '  title: string;'
$lines += '  lat: number;'
$lines += '  lng: number;'
$lines += '  kind: MapPointKind;'
$lines += '  address?: string;'
$lines += '  notes?: string;'
$lines += '};'
$lines += ''
$lines += 'type LocalPointState = {'
$lines += '  seen?: boolean;'
$lines += '  evidence?: string;'
$lines += '};'
$lines += ''
$lines += 'type CallKind = "chamado" | "mutirao";'
$lines += ''
$lines += 'type LocalCall = {'
$lines += '  id: string;'
$lines += '  pointId: string;'
$lines += '  kind: CallKind;'
$lines += '  title: string;'
$lines += '  pedido: string;'
$lines += '  ajuda: string;'
$lines += '  when?: string;'
$lines += '  where?: string;'
$lines += '  createdAt: number;'
$lines += '  done?: boolean;'
$lines += '};'
$lines += ''
$lines += 'function isBrowser() {'
$lines += '  return typeof window !== "undefined";'
$lines += '}'
$lines += ''
$lines += 'function safeRead<T>(key: string, fallback: T): T {'
$lines += '  if (!isBrowser()) return fallback;'
$lines += '  try {'
$lines += '    const raw = window.localStorage.getItem(key);'
$lines += '    if (!raw) return fallback;'
$lines += '    return JSON.parse(raw) as T;'
$lines += '  } catch {'
$lines += '    return fallback;'
$lines += '  }'
$lines += '}'
$lines += ''
$lines += 'function safeWrite<T>(key: string, value: T) {'
$lines += '  if (!isBrowser()) return;'
$lines += '  try {'
$lines += '    window.localStorage.setItem(key, JSON.stringify(value));'
$lines += '  } catch {}'
$lines += '}'
$lines += ''
$lines += 'function useSlug(explicit?: string) {'
$lines += '  const params = useParams() as Record<string, string | string[] | undefined>;'
$lines += '  const raw = explicit ?? params["slug"];'
$lines += '  if (!raw) return "";'
$lines += '  return Array.isArray(raw) ? (raw[0] || "") : raw;'
$lines += '}'
$lines += ''
$lines += 'function uid() {'
$lines += '  return Math.random().toString(16).slice(2) + Date.now().toString(16);'
$lines += '}'
$lines += ''
$lines += 'function kindLabel(k: MapPointKind) {'
$lines += '  if (k === "ponto-critico") return "Ponto crítico";'
$lines += '  if (k === "mutirao") return "Mutirão";'
$lines += '  if (k === "instituicao") return "Instituição";'
$lines += '  if (k === "ponto-eco") return "Ponto ECO";'
$lines += '  return "Outro";'
$lines += '}'
$lines += ''
$lines += 'function googleMapsLink(lat: number, lng: number) {'
$lines += '  const q = encodeURIComponent(lat.toFixed(6) + "," + lng.toFixed(6));'
$lines += '  return "https://www.google.com/maps?q=" + q;'
$lines += '}'
$lines += ''
$lines += 'function clamp(n: number, a: number, b: number) {'
$lines += '  return Math.max(a, Math.min(b, n));'
$lines += '}'
$lines += ''
$lines += 'function fmtDate(ts: number) {'
$lines += '  try {'
$lines += '    return new Date(ts).toLocaleString();'
$lines += '  } catch {'
$lines += '    return String(ts);'
$lines += '  }'
$lines += '}'
$lines += ''
$lines += 'function buildMessage(args: {'
$lines += '  slug: string;'
$lines += '  point: MapPoint;'
$lines += '  call: LocalCall;'
$lines += '}) {'
$lines += '  const s = args.slug || "caderno";'
$lines += '  const p = args.point;'
$lines += '  const c = args.call;'
$lines += '  const lines: string[] = [];'
$lines += '  lines.push("CADERNOS VIVOS — " + s.toUpperCase());'
$lines += '  lines.push("");'
$lines += '  lines.push((c.kind === "mutirao" ? "MUTIRAO" : "CHAMADO") + ": " + c.title);'
$lines += '  lines.push("Local: " + p.title + " (" + p.lat.toFixed(5) + ", " + p.lng.toFixed(5) + ")");'
$lines += '  lines.push("Categoria: " + kindLabel(p.kind));'
$lines += '  if (p.address) lines.push("Endereco: " + p.address);'
$lines += '  lines.push("");'
$lines += '  lines.push("Pedido concreto: " + c.pedido);'
$lines += '  lines.push("Acao de ajuda mutua: " + c.ajuda);'
$lines += '  if (c.when) lines.push("Quando: " + c.when);'
$lines += '  if (c.where) lines.push("Onde: " + c.where);'
$lines += '  lines.push("");'
$lines += '  lines.push("Mapa: /c/" + s + "/mapa");'
$lines += '  lines.push("Abrir no Google Maps: " + googleMapsLink(p.lat, p.lng));'
$lines += '  return lines.join("\\n");'
$lines += '}'
$lines += ''
$lines += 'export default function TerritoryMap(props: {'
$lines += '  points: MapPoint[];'
$lines += '  slug?: string;'
$lines += '}) {'
$lines += '  const slug = useSlug(props.slug);'
$lines += '  const kPoints = "cv:" + (slug || "caderno") + ":map:points:v1";'
$lines += '  const kCalls = "cv:" + (slug || "caderno") + ":map:calls:v1";'
$lines += ''
$lines += '  const [filterKind, setFilterKind] = useState<MapPointKind | "">("");'
$lines += '  const [selectedId, setSelectedId] = useState<string>(props.points[0]?.id || "");'
$lines += ''
$lines += '  const [localPoints, setLocalPoints] = useState<Record<string, LocalPointState>>(() =>'
$lines += '    safeRead<Record<string, LocalPointState>>(kPoints, {})'
$lines += '  );'
$lines += ''
$lines += '  const [calls, setCalls] = useState<LocalCall[]>(() =>'
$lines += '    safeRead<LocalCall[]>(kCalls, [])'
$lines += '  );'
$lines += ''
$lines += '  const points = useMemo(() => {'
$lines += '    const base = props.points || [];'
$lines += '    if (!filterKind) return base;'
$lines += '    return base.filter((p) => p.kind === filterKind);'
$lines += '  }, [props.points, filterKind]);'
$lines += ''
$lines += '  const selected = useMemo(() => {'
$lines += '    const p = (props.points || []).find((x) => x.id === selectedId);'
$lines += '    return p || (props.points || [])[0] || null;'
$lines += '  }, [props.points, selectedId]);'
$lines += ''
$lines += '  const bounds = useMemo(() => {'
$lines += '    const all = props.points || [];'
$lines += '    if (all.length === 0) return null;'
$lines += '    let minLat = all[0].lat, maxLat = all[0].lat, minLng = all[0].lng, maxLng = all[0].lng;'
$lines += '    for (const p of all) {'
$lines += '      minLat = Math.min(minLat, p.lat);'
$lines += '      maxLat = Math.max(maxLat, p.lat);'
$lines += '      minLng = Math.min(minLng, p.lng);'
$lines += '      maxLng = Math.max(maxLng, p.lng);'
$lines += '    }'
$lines += '    // evita divisao por zero'
$lines += '    if (minLat === maxLat) { minLat -= 0.0001; maxLat += 0.0001; }'
$lines += '    if (minLng === maxLng) { minLng -= 0.0001; maxLng += 0.0001; }'
$lines += '    return { minLat, maxLat, minLng, maxLng };'
$lines += '  }, [props.points]);'
$lines += ''
$lines += '  function toXY(p: MapPoint) {'
$lines += '    if (!bounds) return { x: 500, y: 300 };'
$lines += '    const x = (p.lng - bounds.minLng) / (bounds.maxLng - bounds.minLng);'
$lines += '    const y = 1 - (p.lat - bounds.minLat) / (bounds.maxLat - bounds.minLat);'
$lines += '    return { x: clamp(x, 0, 1) * 1000, y: clamp(y, 0, 1) * 600 };'
$lines += '  }'
$lines += ''
$lines += '  function persistPoints(next: Record<string, LocalPointState>) {'
$lines += '    setLocalPoints(next);'
$lines += '    safeWrite(kPoints, next);'
$lines += '  }'
$lines += ''
$lines += '  function persistCalls(next: LocalCall[]) {'
$lines += '    setCalls(next);'
$lines += '    safeWrite(kCalls, next);'
$lines += '  }'
$lines += ''
$lines += '  const [draftKind, setDraftKind] = useState<CallKind>("chamado");'
$lines += '  const [draftTitle, setDraftTitle] = useState<string>("");'
$lines += '  const [draftPedido, setDraftPedido] = useState<string>("");'
$lines += '  const [draftAjuda, setDraftAjuda] = useState<string>("");'
$lines += '  const [draftWhen, setDraftWhen] = useState<string>("");'
$lines += '  const [draftWhere, setDraftWhere] = useState<string>("");'
$lines += '  const [status, setStatus] = useState<"" | "salvo" | "copiado">("");'
$lines += ''
$lines += '  function primeDraftFromPoint(p: MapPoint) {'
$lines += '    const base = (draftKind === "mutirao" ? "Mutirao" : "Chamado") + " — " + p.title;'
$lines += '    if (!draftTitle) setDraftTitle(base);'
$lines += '  }'
$lines += ''
$lines += '  async function copyText(text: string) {'
$lines += '    try {'
$lines += '      await navigator.clipboard.writeText(text);'
$lines += '      setStatus("copiado");'
$lines += '      setTimeout(() => setStatus(""), 1200);'
$lines += '    } catch {}'
$lines += '  }'
$lines += ''
$lines += '  function addCall(point: MapPoint) {'
$lines += '    const pedido = draftPedido.trim();'
$lines += '    const ajuda = draftAjuda.trim();'
$lines += '    const title = (draftTitle || (draftKind === "mutirao" ? "Mutirao" : "Chamado") + " — " + point.title).trim();'
$lines += '    if (!pedido || !ajuda || !title) {'
$lines += '      setStatus("");'
$lines += '      return;'
$lines += '    }'
$lines += '    const call: LocalCall = {'
$lines += '      id: uid(),'
$lines += '      pointId: point.id,'
$lines += '      kind: draftKind,'
$lines += '      title,'
$lines += '      pedido,'
$lines += '      ajuda,'
$lines += '      when: draftWhen.trim() || undefined,'
$lines += '      where: draftWhere.trim() || undefined,'
$lines += '      createdAt: Date.now(),'
$lines += '      done: false,'
$lines += '    };'
$lines += '    const next = [call, ...calls];'
$lines += '    persistCalls(next);'
$lines += '    setStatus("salvo");'
$lines += '    setTimeout(() => setStatus(""), 1200);'
$lines += '  }'
$lines += ''
$lines += '  function toggleSeen(pointId: string) {'
$lines += '    const cur = localPoints[pointId] || {};'
$lines += '    const next: Record<string, LocalPointState> = { ...localPoints, [pointId]: { ...cur, seen: !cur.seen } };'
$lines += '    persistPoints(next);'
$lines += '  }'
$lines += ''
$lines += '  function saveEvidence(pointId: string, evidence: string) {'
$lines += '    const cur = localPoints[pointId] || {};'
$lines += '    const next: Record<string, LocalPointState> = { ...localPoints, [pointId]: { ...cur, evidence } };'
$lines += '    persistPoints(next);'
$lines += '    setStatus("salvo");'
$lines += '    setTimeout(() => setStatus(""), 1200);'
$lines += '  }'
$lines += ''
$lines += '  function markDone(callId: string, done: boolean) {'
$lines += '    const next = calls.map((c) => (c.id === callId ? { ...c, done } : c));'
$lines += '    persistCalls(next);'
$lines += '  }'
$lines += ''
$lines += '  function removeCall(callId: string) {'
$lines += '    const next = calls.filter((c) => c.id !== callId);'
$lines += '    persistCalls(next);'
$lines += '  }'
$lines += ''
$lines += '  const activeCalls = useMemo(() => calls.filter((c) => !c.done), [calls]);'
$lines += ''
$lines += '  return ('
$lines += '    <div className="grid gap-4 lg:grid-cols-[1fr_420px]">'
$lines += '      <section className="card p-5">'
$lines += '        <div className="flex flex-wrap items-end justify-between gap-3">'
$lines += '          <div>'
$lines += '            <h2 className="text-xl font-semibold">Mapa do território</h2>'
$lines += '            <p className="muted mt-2">Ponto crítico vira organização: ver, registrar, pedir, agir.</p>'
$lines += '          </div>'
$lines += '          <div className="flex items-center gap-2">'
$lines += '            <div className="text-sm muted">Filtrar:</div>'
$lines += '            <select'
$lines += '              className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none focus:border-white/20"'
$lines += '              value={filterKind}'
$lines += '              onChange={(e) => setFilterKind((e.target.value as MapPointKind) || "")}'
$lines += '            >'
$lines += '              <option value="">Tudo</option>'
$lines += '              <option value="ponto-critico">Ponto critico</option>'
$lines += '              <option value="mutirao">Mutirao</option>'
$lines += '              <option value="instituicao">Instituicao</option>'
$lines += '              <option value="ponto-eco">Ponto ECO</option>'
$lines += '              <option value="outro">Outro</option>'
$lines += '            </select>'
$lines += '          </div>'
$lines += '        </div>'
$lines += ''
$lines += '        <div className="mt-4 rounded-2xl border border-white/10 bg-black/10 p-3">'
$lines += '          <svg viewBox="0 0 1000 600" className="w-full h-[360px]">'
$lines += '            <rect x="0" y="0" width="1000" height="600" fill="transparent" />'
$lines += '            {bounds && (props.points || []).map((p) => {'
$lines += '              if (filterKind && p.kind !== filterKind) return null;'
$lines += '              const xy = toXY(p);'
$lines += '              const isSel = selected && selected.id === p.id;'
$lines += '              const seen = !!localPoints[p.id]?.seen;'
$lines += '              const r = isSel ? 10 : 7;'
$lines += '              return ('
$lines += '                <g key={p.id} onClick={() => { setSelectedId(p.id); primeDraftFromPoint(p); }} style={{ cursor: "pointer" }}>'
$lines += '                  <circle cx={xy.x} cy={xy.y} r={r} fill="currentColor" opacity={seen ? 0.95 : 0.65} />'
$lines += '                  {isSel ? <circle cx={xy.x} cy={xy.y} r={r + 8} fill="none" stroke="currentColor" opacity={0.35} strokeWidth={2} /> : null}'
$lines += '                </g>'
$lines += '              );'
$lines += '            })}'
$lines += '          </svg>'
$lines += '        </div>'
$lines += ''
$lines += '        <div className="mt-4">'
$lines += '          <div className="text-sm muted">Pontos ({String(points.length)})</div>'
$lines += '          <div className="mt-2 grid gap-2">'
$lines += '            {points.map((p) => {'
$lines += '              const isSel = selected && selected.id === p.id;'
$lines += '              const seen = !!localPoints[p.id]?.seen;'
$lines += '              return ('
$lines += '                <button'
$lines += '                  key={p.id}'
$lines += '                  onClick={() => { setSelectedId(p.id); primeDraftFromPoint(p); }}'
$lines += '                  className="card px-3 py-3 text-left hover:bg-white/5 transition"'
$lines += '                >'
$lines += '                  <div className="flex items-center justify-between gap-2">'
$lines += '                    <div className="font-semibold">{p.title}</div>'
$lines += '                    <div className="text-xs muted">{kindLabel(p.kind)}{seen ? " • confirmado" : ""}</div>'
$lines += '                  </div>'
$lines += '                  {p.address ? <div className="text-sm muted mt-1">{p.address}</div> : null}'
$lines += '                </button>'
$lines += '              );'
$lines += '            })}'
$lines += '          </div>'
$lines += '        </div>'
$lines += '      </section>'
$lines += ''
$lines += '      <aside className="space-y-4">'
$lines += '        <section className="card p-5">'
$lines += '          <div className="flex items-center justify-between gap-2">'
$lines += '            <h3 className="text-lg font-semibold">Chamados ativos</h3>'
$lines += '            <div className="text-xs muted">{String(activeCalls.length)}</div>'
$lines += '          </div>'
$lines += '          <p className="muted mt-2">Tudo fica salvo no seu aparelho. Copie e jogue no WhatsApp.</p>'
$lines += '          <div className="mt-3 grid gap-2">'
$lines += '            {activeCalls.length === 0 ? ('
$lines += '              <div className="text-sm muted">Nenhum chamado ainda.</div>'
$lines += '            ) : ('
$lines += '              activeCalls.slice(0, 6).map((c) => {'
$lines += '                const p = (props.points || []).find((x) => x.id === c.pointId);'
$lines += '                return ('
$lines += '                  <div key={c.id} className="rounded-2xl border border-white/10 bg-black/10 p-3">'
$lines += '                    <div className="text-xs muted">{c.kind === "mutirao" ? "MUTIRAO" : "CHAMADO"} • {fmtDate(c.createdAt)}</div>'
$lines += '                    <div className="font-semibold mt-1">{c.title}</div>'
$lines += '                    <div className="text-sm muted mt-1">{p ? p.title : "Ponto"} • {p ? kindLabel(p.kind) : ""}</div>'
$lines += '                    <div className="mt-2 flex flex-wrap gap-2">'
$lines += '                      <button className="card px-3 py-2 hover:bg-white/10 transition" onClick={() => { if (!p) return; copyText(buildMessage({ slug: slug || "caderno", point: p, call: c })); }}>'
$lines += '                        <span className="accent">Copiar texto</span>'
$lines += '                      </button>'
$lines += '                      <button className="card px-3 py-2 hover:bg-white/10 transition" onClick={() => markDone(c.id, true)}>'
$lines += '                        Concluir'
$lines += '                      </button>'
$lines += '                      <button className="card px-3 py-2 hover:bg-white/10 transition" onClick={() => removeCall(c.id)}>'
$lines += '                        Apagar'
$lines += '                      </button>'
$lines += '                    </div>'
$lines += '                  </div>'
$lines += '                );'
$lines += '              })'
$lines += '            )}'
$lines += '          </div>'
$lines += '          <div className="mt-3">'
$lines += '            <button'
$lines += '              className="card px-3 py-2 hover:bg-white/10 transition text-sm"'
$lines += '              onClick={() => copyText(JSON.stringify({ slug: slug || "caderno", calls }, null, 2))}'
$lines += '            >'
$lines += '              <span className="accent">{status === "copiado" ? "Copiado!" : "Copiar JSON"}</span>'
$lines += '            </button>'
$lines += '          </div>'
$lines += '        </section>'
$lines += ''
$lines += '        <section className="card p-5">'
$lines += '          <h3 className="text-lg font-semibold">Ponto selecionado</h3>'
$lines += '          {!selected ? ('
$lines += '            <div className="muted mt-2">Sem pontos no mapa.</div>'
$lines += '          ) : ('
$lines += '            <div className="mt-3 space-y-4">'
$lines += '              <div>'
$lines += '                <div className="text-xs muted">{selected.id}</div>'
$lines += '                <div className="text-xl font-semibold mt-1">{selected.title}</div>'
$lines += '                <div className="muted mt-1">{kindLabel(selected.kind)} • {selected.lat.toFixed(6)}, {selected.lng.toFixed(6)}</div>'
$lines += '                {selected.address ? <div className="text-sm muted mt-1">{selected.address}</div> : null}'
$lines += '                <div className="mt-3 flex flex-wrap gap-2">'
$lines += '                  <a className="card px-3 py-2 hover:bg-white/10 transition text-sm" href={googleMapsLink(selected.lat, selected.lng)} target="_blank" rel="noreferrer">'
$lines += '                    <span className="accent">Abrir no Maps</span>'
$lines += '                  </a>'
$lines += '                  <button className="card px-3 py-2 hover:bg-white/10 transition text-sm" onClick={() => toggleSeen(selected.id)}>'
$lines += '                    {localPoints[selected.id]?.seen ? "Confirmado (remover)" : "Eu vi tambem"}'
$lines += '                  </button>'
$lines += '                </div>'
$lines += '              </div>'
$lines += ''
$lines += '              <div className="rounded-2xl border border-white/10 bg-black/10 p-4">'
$lines += '                <div className="font-semibold">Evidencia leve</div>'
$lines += '                <div className="text-sm muted mt-1">Link, frase curta, referencia. Sem textao.</div>'
$lines += '                <textarea'
$lines += '                  className="mt-3 w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none focus:border-white/20"'
$lines += '                  rows={3}'
$lines += '                  value={localPoints[selected.id]?.evidence || ""}'
$lines += '                  onChange={(e) => {'
$lines += '                    const v = e.target.value;'
$lines += '                    const cur = localPoints[selected.id] || {};'
$lines += '                    setLocalPoints({ ...localPoints, [selected.id]: { ...cur, evidence: v } });'
$lines += '                  }}'
$lines += '                  placeholder="Ex: foto do local (link), data, observacao objetiva..."'
$lines += '                />'
$lines += '                <div className="mt-2 flex flex-wrap gap-2">'
$lines += '                  <button className="card px-3 py-2 hover:bg-white/10 transition text-sm" onClick={() => saveEvidence(selected.id, (localPoints[selected.id]?.evidence || "").slice(0, 600))}>'
$lines += '                    <span className="accent">{status === "salvo" ? "Salvo!" : "Salvar evidencia"}</span>'
$lines += '                  </button>'
$lines += '                </div>'
$lines += '              </div>'
$lines += ''
$lines += '              <div className="rounded-2xl border border-white/10 bg-black/10 p-4">'
$lines += '                <div className="font-semibold">Chamado / Mutirao (30s)</div>'
$lines += '                <div className="grid gap-3 mt-3">'
$lines += '                  <div className="grid gap-2">'
$lines += '                    <div className="text-sm muted">Tipo</div>'
$lines += '                    <select'
$lines += '                      className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm outline-none focus:border-white/20"'
$lines += '                      value={draftKind}'
$lines += '                      onChange={(e) => setDraftKind((e.target.value as CallKind) || "chamado")}'
$lines += '                    >'
$lines += '                      <option value="chamado">Chamado</option>'
$lines += '                      <option value="mutirao">Mutirao</option>'
$lines += '                    </select>'
$lines += '                  </div>'
$lines += '                  <div className="grid gap-2">'
$lines += '                    <div className="text-sm muted">Titulo</div>'
$lines += '                    <input'
$lines += '                      className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 outline-none focus:border-white/20"'
$lines += '                      value={draftTitle}'
$lines += '                      onChange={(e) => setDraftTitle(e.target.value)}'
$lines += '                      placeholder={(draftKind === "mutirao" ? "Mutirao" : "Chamado") + " — " + selected.title}'
$lines += '                    />'
$lines += '                  </div>'
$lines += '                  <div className="grid gap-2">'
$lines += '                    <div className="text-sm muted">Pedido concreto</div>'
$lines += '                    <textarea'
$lines += '                      className="w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none focus:border-white/20"'
$lines += '                      rows={3}'
$lines += '                      value={draftPedido}'
$lines += '                      onChange={(e) => setDraftPedido(e.target.value)}'
$lines += '                      placeholder="O que deve acontecer, por quem, e quando?"'
$lines += '                    />'
$lines += '                  </div>'
$lines += '                  <div className="grid gap-2">'
$lines += '                    <div className="text-sm muted">Acao simples de ajuda mutua</div>'
$lines += '                    <textarea'
$lines += '                      className="w-full rounded-xl border border-white/10 bg-black/20 p-3 outline-none focus:border-white/20"'
$lines += '                      rows={3}'
$lines += '                      value={draftAjuda}'
$lines += '                      onChange={(e) => setDraftAjuda(e.target.value)}'
$lines += '                      placeholder="Algo pratico (2 a 10 min) que qualquer pessoa consiga fazer."'
$lines += '                    />'
$lines += '                  </div>'
$lines += '                  <div className="grid gap-3 sm:grid-cols-2">'
$lines += '                    <div className="grid gap-2">'
$lines += '                      <div className="text-sm muted">Quando (opcional)</div>'
$lines += '                      <input'
$lines += '                        className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 outline-none focus:border-white/20"'
$lines += '                        value={draftWhen}'
$lines += '                        onChange={(e) => setDraftWhen(e.target.value)}'
$lines += '                        placeholder="Ex: Sab 10h (05/01)"'
$lines += '                      />'
$lines += '                    </div>'
$lines += '                    <div className="grid gap-2">'
$lines += '                      <div className="text-sm muted">Onde (opcional)</div>'
$lines += '                      <input'
$lines += '                        className="w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2 outline-none focus:border-white/20"'
$lines += '                        value={draftWhere}'
$lines += '                        onChange={(e) => setDraftWhere(e.target.value)}'
$lines += '                        placeholder="Ponto de encontro / referencia"'
$lines += '                      />'
$lines += '                    </div>'
$lines += '                  </div>'
$lines += '                </div>'
$lines += ''
$lines += '                <div className="mt-3 flex flex-wrap gap-2">'
$lines += '                  <button className="card px-3 py-2 hover:bg-white/10 transition" onClick={() => addCall(selected)}>'
$lines += '                    <span className="accent">{status === "salvo" ? "Salvo!" : "Salvar"}</span>'
$lines += '                  </button>'
$lines += '                  <button'
$lines += '                    className="card px-3 py-2 hover:bg-white/10 transition"'
$lines += '                    onClick={() => {'
$lines += '                      const pedido = draftPedido.trim();'
$lines += '                      const ajuda = draftAjuda.trim();'
$lines += '                      const title = (draftTitle || (draftKind === "mutirao" ? "Mutirao" : "Chamado") + " — " + selected.title).trim();'
$lines += '                      if (!pedido || !ajuda || !title) return;'
$lines += '                      const tmp: LocalCall = {'
$lines += '                        id: "tmp",'
$lines += '                        pointId: selected.id,'
$lines += '                        kind: draftKind,'
$lines += '                        title,'
$lines += '                        pedido,'
$lines += '                        ajuda,'
$lines += '                        when: draftWhen.trim() || undefined,'
$lines += '                        where: draftWhere.trim() || undefined,'
$lines += '                        createdAt: Date.now(),'
$lines += '                        done: false,'
$lines += '                      };'
$lines += '                      copyText(buildMessage({ slug: slug || "caderno", point: selected, call: tmp }));'
$lines += '                    }}'
$lines += '                  >'
$lines += '                    <span className="accent">{status === "copiado" ? "Copiado!" : "Copiar texto"}</span>'
$lines += '                  </button>'
$lines += '                </div>'
$lines += '              </div>'
$lines += '            </div>'
$lines += '          )}'
$lines += '        </section>'
$lines += '      </aside>'
$lines += '    </div>'
$lines += '  );'
$lines += '}'

WriteUtf8NoBom $mapComp ($lines -join "`n")
WL "[OK] TerritoryMap.tsx refeito (slug opcional + evidencia + chamado/mutirao)."

# -------------------------
# REPORT
# -------------------------
$repDir = Join-Path $repo "reports"
EnsureDir $repDir
$now = Get-Date -Format "yyyy-MM-dd HH:mm"
$reportPath = Join-Path $repDir "cv-4-mapa-chamados-mutirao-v0_4.md"
$r = @()
$r += ("# CV-4 — Mapa: Ponto critico, evidencia leve, chamado e mutirao — " + $now)
$r += ""
$r += "## O que mudou"
$r += " - TerritoryMap agora aceita slug opcional e infere via useParams"
$r += " - Confirmacao local por ponto (Eu vi tambem)"
$r += " - Evidencia leve por ponto (texto/link curto) salva no aparelho"
$r += " - Chamado / Mutirao 30s com pedido concreto + ajuda mutua"
$r += " - Copiar texto pronto e Copiar JSON"
$r += ""
$r += "## Onde usar"
$r += " - Abra /c/poluicao-vr/mapa"
$r += ""
$r += "## Proximo tijolo (CV-5)"
$r += " - Recibo de mutirao (antes/depois, checklist) e export em card 3:4 (OG/share)"
WriteUtf8NoBom $reportPath ($r -join "`n")
WL ("[OK] Report: " + $reportPath)

# -------------------------
# VERIFY
# -------------------------
WL "[VERIFY] npm run lint..."
RunNative $repo $npmExe @("run","lint")

if (-not $SkipBuild) {
  WL "[VERIFY] npm run build..."
  RunNative $repo $npmExe @("run","build")
} else {
  WL "[VERIFY] build pulado (-SkipBuild)."
}

WL ""
WL "[OK] CV-4 pronto. Rode npm run dev e abra /c/poluicao-vr/mapa"