# CV — V2 Tijolo D3 — DebateV2 (hash focus + cards + crosslinks) — v0_29
# DIAG → PATCH → VERIFY → REPORT
$ErrorActionPreference = "Stop"

$repo = Get-Location
$boot = Join-Path $repo "tools\_bootstrap.ps1"
if (-not (Test-Path -LiteralPath $boot)) { throw "[STOP] tools/_bootstrap.ps1 não encontrado. Rode o tijolo infra antes." }
. $boot

Write-Host ("[DIAG] Repo: " + $repo)

# ---------------------------
# 1) src/components/v2/DebateV2.tsx (client)
# ---------------------------
$compPath = Join-Path $repo "src\components\v2\DebateV2.tsx"
$bk1 = BackupFile $compPath

$compLines = @(
'"use client";',
'',
'import React, { useEffect, useMemo, useState } from "react";',
'import Link from "next/link";',
'',
'type AnyObj = Record<string, unknown>;',
'function isObj(v: unknown): v is AnyObj {',
'  return typeof v === "object" && v !== null && !Array.isArray(v);',
'}',
'function asStr(v: unknown): string | null {',
'  return typeof v === "string" ? v : null;',
'}',
'function asStrArr(v: unknown): string[] {',
'  if (Array.isArray(v)) return v.map(asStr).filter((x): x is string => !!x);',
'  const s = asStr(v);',
'  if (!s) return [];',
'  return s.split(",").map((x) => x.trim()).filter(Boolean);',
'}',
'function getFirst(obj: AnyObj, keys: string[]): unknown {',
'  for (const k of keys) {',
'    if (Object.prototype.hasOwnProperty.call(obj, k)) return obj[k];',
'  }',
'  return undefined;',
'}',
'',
'type DebateItem = {',
'  id: string;',
'  title: string;',
'  body: string | null;',
'  tags: string[];',
'  links: string[];',
'  related: string[];',
'  kind: string;',
'};',
'',
'function readHashId(): string {',
'  if (typeof window === "undefined") return "";',
'  const h = window.location.hash || "";',
'  if (!h) return "";',
'  const v = h.startsWith("#") ? h.slice(1) : h;',
'  try { return decodeURIComponent(v); } catch { return v; }',
'}',
'function toDomId(id: string): string {',
'  return ("d-" + id).replace(/[^A-Za-z0-9_-]/g, "_");',
'}',
'',
'function extractItems(debate: unknown): AnyObj[] {',
'  if (Array.isArray(debate)) return debate.filter(isObj);',
'  if (isObj(debate)) {',
'    const items = (debate as AnyObj).items;',
'    if (Array.isArray(items)) return items.filter(isObj);',
'    const threads = (debate as AnyObj).threads;',
'    if (Array.isArray(threads)) return threads.filter(isObj);',
'    const list = (debate as AnyObj).list;',
'    if (Array.isArray(list)) return list.filter(isObj);',
'    const vals = Object.values(debate).filter(isObj) as AnyObj[];',
'    if (vals.length > 0) return vals;',
'  }',
'  return [];',
'}',
'',
'function toItem(obj: AnyObj, idx: number): DebateItem {',
'  const id = asStr(getFirst(obj, ["id","slug","key","uid"])) ?? ("topico-" + String(idx));',
'  const title = asStr(getFirst(obj, ["title","name","label","tema"])) ?? id;',
'  const body = asStr(getFirst(obj, ["body","texto","text","desc","description","resumo","summary"])) ?? null;',
'  const tags = asStrArr(getFirst(obj, ["tags","tag","labels","marcadores"]));',
'  const links = asStrArr(getFirst(obj, ["links","refs","referencias"]));',
'  const related = asStrArr(getFirst(obj, ["related","rel","ids","vinculos","vinculados"]));',
'  const kind = (asStr(getFirst(obj, ["kind","type"])) ?? "topico");',
'  return { id, title, body, tags, links, related, kind };',
'}',
'',
'export default function DebateV2(props: { slug: string; title?: string; debate?: unknown }) {',
'  const slug = props.slug;',
'  const title = props.title ?? slug;',
'',
'  const items = useMemo(() => {',
'    const arr = extractItems(props.debate);',
'    return arr.map((o, i) => toItem(o, i));',
'  }, [props.debate]);',
'',
'  const [focus, setFocus] = useState<string>(() => readHashId());',
'  const [q, setQ] = useState<string>("");',
'  const [copied, setCopied] = useState<string>("");',
'',
'  useEffect(() => {',
'    const onHash = () => setFocus(readHashId());',
'    window.addEventListener("hashchange", onHash);',
'    return () => window.removeEventListener("hashchange", onHash);',
'  }, []);',
'',
'  useEffect(() => {',
'    if (!focus) return;',
'    const el = document.getElementById(toDomId(focus));',
'    if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });',
'  }, [focus]);',
'',
'  const base = typeof window !== "undefined" ? window.location.origin : "";',
'',
'  const filtered = useMemo(() => {',
'    const qq = q.trim().toLowerCase();',
'    if (!qq) return items;',
'    return items.filter((it) => {',
'      if (it.id.toLowerCase().includes(qq)) return true;',
'      if (it.title.toLowerCase().includes(qq)) return true;',
'      if ((it.body ?? "").toLowerCase().includes(qq)) return true;',
'      if (it.tags.some((t) => t.toLowerCase().includes(qq))) return true;',
'      return false;',
'    });',
'  }, [items, q]);',
'',
'  return (',
'    <section style={{ padding: 12 }}>',
'      <div style={{ marginBottom: 12, opacity: 0.9 }}>',
'        <div style={{ fontSize: 13, opacity: 0.85 }}>Caderno</div>',
'        <h1 style={{ fontSize: 22, margin: "2px 0 0 0" }}>{title}</h1>',
'        <div style={{ fontSize: 13, opacity: 0.8, marginTop: 6 }}>',
'          Debate em tópicos. Use o hash no link (ex: #id) para focar um tópico.',
'        </div>',
'      </div>',
'',
'      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginBottom: 12, alignItems: "center" }}>',
'        <input',
'          value={q}',
'          onChange={(e) => setQ(e.target.value)}',
'          placeholder="buscar (título, texto, tags)"',
'          style={{',
'            flex: "1 1 260px",',
'            border: "1px solid rgba(255,255,255,0.14)",',
'            background: "transparent",',
'            color: "inherit",',
'            borderRadius: 10,',
'            padding: "8px 10px",',
'            outline: "none",',
'          }}',
'        />',
'        <div style={{ fontSize: 12, opacity: 0.75 }}>{filtered.length}/{items.length}</div>',
'      </div>',
'',
'      {items.length === 0 ? (',
'        <div style={{ opacity: 0.8, padding: 12, border: "1px solid rgba(255,255,255,0.08)", borderRadius: 10 }}>',
'          Nenhum tópico encontrado em debate.',
'        </div>',
'      ) : (',
'        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>',
'          {filtered.map((it) => {',
'            const domId = toDomId(it.id);',
'            const isFocus = focus && (focus === it.id);',
'            const shareUrl = base + "/c/" + slug + "/v2/debate#" + encodeURIComponent(it.id);',
'',
'            return (',
'              <article',
'                key={it.id}',
'                id={domId}',
'                style={{',
'                  border: "1px solid rgba(255,255,255,0.10)",',
'                  borderRadius: 12,',
'                  padding: 12,',
'                  background: isFocus ? "rgba(255,255,255,0.06)" : "transparent",',
'                }}',
'              >',
'                <div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between", gap: 10 }}>',
'                  <div style={{ fontSize: 12, opacity: 0.75 }}>{it.kind}</div>',
'                  <div style={{ fontSize: 12, opacity: 0.75 }}>{it.id}</div>',
'                </div>',
'',
'                <h2 style={{ margin: "6px 0 0 0", fontSize: 18 }}>{it.title}</h2>',
'',
'                {it.body ? (',
'                  <p style={{ margin: "8px 0 0 0", opacity: 0.9, lineHeight: 1.45 }}>',
'                    {it.body}',
'                  </p>',
'                ) : null}',
'',
'                {it.tags.length > 0 ? (',
'                  <div style={{ marginTop: 10, display: "flex", gap: 6, flexWrap: "wrap" }}>',
'                    {it.tags.map((t, i) => (',
'                      <span',
'                        key={t + String(i)}',
'                        style={{ fontSize: 12, padding: "2px 8px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.10)", opacity: 0.9 }}',
'                      >',
'                        {t}',
'                      </span>',
'                    ))}',
'                  </div>',
'                ) : null}',
'',
'                <div style={{ marginTop: 12, display: "flex", gap: 10, flexWrap: "wrap" }}>',
'                  <Link href={"/c/" + slug + "/v2/mapa#" + encodeURIComponent(it.id)} style={{ textDecoration: "underline", opacity: 0.9 }}>',
'                    Ver no Mapa',
'                  </Link>',
'                  <Link href={"/c/" + slug + "/v2/linha#" + encodeURIComponent(it.id)} style={{ textDecoration: "underline", opacity: 0.9 }}>',
'                    Ver na Linha',
'                  </Link>',
'                  <Link href={"/c/" + slug + "/v2/provas#" + encodeURIComponent(it.id)} style={{ textDecoration: "underline", opacity: 0.9 }}>',
'                    Ver Provas',
'                  </Link>',
'',
'                  <button',
'                    type="button"',
'                    onClick={async () => {',
'                      try {',
'                        await navigator.clipboard.writeText(shareUrl);',
'                        setCopied(it.id);',
'                        const el = document.getElementById(domId);',
'                        if (el) el.scrollIntoView({ behavior: "smooth", block: "start" });',
'                        setTimeout(() => setCopied(""), 1200);',
'                      } catch {',
'                        /* noop */',
'                      }',
'                    }}',
'                    style={{',
'                      border: "1px solid rgba(255,255,255,0.12)",',
'                      background: "transparent",',
'                      color: "inherit",',
'                      borderRadius: 10,',
'                      padding: "6px 10px",',
'                      cursor: "pointer",',
'                      opacity: 0.95,',
'                    }}',
'                  >',
'                    {copied === it.id ? "Copiado" : "Copiar link"}',
'                  </button>',
'',
'                  {it.links.length > 0 ? (',
'                    <a href={it.links[0]} target="_blank" rel="noreferrer" style={{ textDecoration: "underline", opacity: 0.95 }}>',
'                      Abrir referência',
'                    </a>',
'                  ) : null}',
'                </div>',
'',
'                {it.related.length > 0 ? (',
'                  <div style={{ marginTop: 10, fontSize: 12, opacity: 0.85 }}>',
'                    Relacionados: {it.related.join(", ")}',
'                  </div>',
'                ) : null}',
'              </article>',
'            );',
'          })}',
'        </div>',
'      )}',
'    </section>',
'  );',
'}'
)

EnsureDir (Split-Path -Parent $compPath)
WriteLinesUtf8NoBom $compPath $compLines
Write-Host ("[OK] wrote: " + $compPath)
if ($bk1) { Write-Host ("[BK] " + $bk1) }

# ---------------------------
# 2) src/app/c/[slug]/v2/debate/page.tsx (server)
# ---------------------------
$pagePath = Join-Path $repo "src\app\c\[slug]\v2\debate\page.tsx"
$bk2 = BackupFile $pagePath

$pageLines = @(
'import V2Nav from "@/components/v2/V2Nav";',
'import DebateV2 from "@/components/v2/DebateV2";',
'import { loadCadernoV2 } from "@/lib/v2";',
'',
'type AnyObj = Record<string, unknown>;',
'function isObj(v: unknown): v is AnyObj {',
'  return typeof v === "object" && v !== null && !Array.isArray(v);',
'}',
'function getProp(obj: unknown, key: string): unknown {',
'  if (!isObj(obj)) return undefined;',
'  return Object.prototype.hasOwnProperty.call(obj, key) ? obj[key] : undefined;',
'}',
'',
'export default async function Page(props: { params: { slug: string } }) {',
'  const slug = props.params.slug;',
'  const c = await loadCadernoV2(slug);',
'  const meta = getProp(c, "meta");',
'  const title = (isObj(meta) && typeof meta.title === "string" ? meta.title : slug);',
'  const debate = getProp(c, "debate") ?? getProp(c, "discussao") ?? getProp(c, "discussion") ?? null;',
'',
'  return (',
'    <main style={{ padding: 12 }}>',
'      <V2Nav slug={slug} active="debate" />',
'      <DebateV2 slug={slug} title={title} debate={debate} />',
'    </main>',
'  );',
'}'
)

EnsureDir (Split-Path -Parent $pagePath)
WriteLinesUtf8NoBom $pagePath $pageLines
Write-Host ("[OK] wrote: " + $pagePath)
if ($bk2) { Write-Host ("[BK] " + $bk2) }

# ---------------------------
# 3) VERIFY
# ---------------------------
RunPs1 (Join-Path $repo "tools\cv-verify.ps1")

# ---------------------------
# 4) REPORT
# ---------------------------
$reportText = @(
'# CV — V2 Tijolo D3 v0_29 — DebateV2 (hash focus)',
'',
'## O que entrou',
'- DebateV2 client resiliente (props unknown, extrai items/threads/list).',
'- Foco por hash sem mutar window.location (scrollIntoView).',
'- Busca local (título, texto, tags).',
'- Links cruzados: Mapa, Linha, Provas + copiar link com hash.',
'- Page server /c/[slug]/v2/debate com meta.title ?? slug e debate/discussao fallback.',
'',
'## Arquivos',
'- src/components/v2/DebateV2.tsx',
'- src/app/c/[slug]/v2/debate/page.tsx',
'',
'## Verify',
'- tools/cv-verify.ps1 (guard + lint + build)',
''
) -join "`n"

WriteReport "cv-v2-tijolo-d3-debate-v2-hashfocus-v0_29.md" $reportText | Out-Null
Write-Host "[OK] v0_29 aplicado e verificado."