# CV — V2 Hotfix — HomeV2 + /v2 page sem "any" + V2Nav robusto — v0_28
# DIAG → PATCH → VERIFY → REPORT
$ErrorActionPreference = "Stop"

$repo = Get-Location
$bootstrap = Join-Path $repo "tools\_bootstrap.ps1"
if (-not (Test-Path -LiteralPath $bootstrap)) { throw "[STOP] tools/_bootstrap.ps1 não encontrado." }
. $bootstrap

Write-Host ("[DIAG] Repo: " + $repo)

$homeCompPath = Join-Path $repo "src\components\v2\HomeV2.tsx"
$v2HomePagePath = Join-Path $repo "src\app\c\[slug]\v2\page.tsx"
$v2NavPath = Join-Path $repo "src\components\v2\V2Nav.tsx"

EnsureDir (Split-Path -Parent $homeCompPath)
EnsureDir (Split-Path -Parent $v2HomePagePath)
EnsureDir (Split-Path -Parent $v2NavPath)

# --- 1) V2Nav robusto (active opcional, sem unions frágeis) ---
$bkNav = BackupFile $v2NavPath
$v2NavLines = @(
  'import Link from "next/link";',
  '',
  'type Props = {',
  '  slug: string;',
  '  active?: string;',
  '};',
  '',
  'export default function V2Nav(props: Props) {',
  '  const slug = props.slug;',
  '  const active = props.active || "";',
  '  const base = "/c/" + slug + "/v2";',
  '',
  '  const items = [',
  '    { key: "home", label: "V2", href: base },',
  '    { key: "mapa", label: "Mapa", href: base + "/mapa" },',
  '    { key: "debate", label: "Debate", href: base + "/debate" },',
  '    { key: "provas", label: "Provas", href: base + "/provas" },',
  '    { key: "trilhas", label: "Trilhas", href: base + "/trilhas" },',
  '    { key: "linha-do-tempo", label: "Linha do tempo", href: base + "/linha-do-tempo" }',
  '  ];',
  '',
  '  return (',
  '    <nav style={{',
  '      display: "flex",',
  '      gap: 10,',
  '      flexWrap: "wrap",',
  '      alignItems: "center",',
  '      padding: "10px 12px",',
  '      border: "1px solid rgba(255,255,255,0.10)",',
  '      borderRadius: 12,',
  '      background: "rgba(0,0,0,0.35)"',
  '    }}>',
  '      {items.map((it) => {',
  '        const on = active === it.key;',
  '        return (',
  '          <Link',
  '            key={it.key}',
  '            href={it.href}',
  '            style={{',
  '              textDecoration: "none",',
  '              padding: "6px 10px",',
  '              borderRadius: 10,',
  '              border: "1px solid rgba(255,255,255,0.12)",',
  '              background: on ? "rgba(255,255,255,0.10)" : "transparent",',
  '              color: "inherit",',
  '              opacity: on ? 1 : 0.85',
  '            }}',
  '          >',
  '            {it.label}',
  '          </Link>',
  '        );',
  '      })}',
  '    </nav>',
  '  );',
  '}'
)
WriteLinesUtf8NoBom $v2NavPath $v2NavLines
Write-Host ("[OK] wrote: " + $v2NavPath)
if ($bkNav) { Write-Host ("[BK] " + $bkNav) }

# --- 2) HomeV2 sem any (aceita JsonValue + counts opcionais) ---
$bkHome = BackupFile $homeCompPath
$homeLines = @(
  'import Link from "next/link";',
  'import type { JsonValue } from "@/lib/v2/types";',
  '',
  'type Counts = {',
  '  nodes?: number;',
  '  edges?: number;',
  '  provas?: number;',
  '  threads?: number;',
  '  trilhas?: number;',
  '};',
  '',
  'type Props = {',
  '  slug: string;',
  '  title: string;',
  '  panorama: JsonValue | null;',
  '  counts?: Counts;',
  '};',
  '',
  'function isObj(v: unknown): v is Record<string, unknown> {',
  '  return !!v && typeof v === "object" && !Array.isArray(v);',
  '}',
  '',
  'function asObj(v: JsonValue | null): Record<string, JsonValue> | null {',
  '  if (!v || typeof v !== "object" || Array.isArray(v)) return null;',
  '  return v as Record<string, JsonValue>;',
  '}',
  '',
  'function asArr(v: JsonValue | null): JsonValue[] | null {',
  '  return Array.isArray(v) ? (v as JsonValue[]) : null;',
  '}',
  '',
  'function pickFirstString(v: JsonValue | null): string {',
  '  if (typeof v === "string") return v;',
  '  const o = asObj(v);',
  '  if (o) {',
  '    for (const k of ["resumo", "descricao", "descrição", "subtitle", "subtitulo", "subtítulo", "pitch"]) {',
  '      const x = o[k];',
  '      if (typeof x === "string" && x.trim().length > 0) return x;',
  '    }',
  '  }',
  '  return "";',
  '}',
  '',
  'function pickFios(panorama: JsonValue | null): string[] {',
  '  const o = asObj(panorama);',
  '  if (!o) return [];',
  '  const keys = ["fiosQuentes", "fios", "hot", "destaques", "tags"];',
  '  for (const k of keys) {',
  '    const v = o[k] ?? null;',
  '    const a = asArr(v);',
  '    if (a) {',
  '      const s = a.filter((x) => typeof x === "string").map((x) => String(x).trim()).filter(Boolean);',
  '      if (s.length > 0) return s;',
  '    }',
  '    if (isObj(v) && Array.isArray((v as any).items)) {',
  '      const items = (v as any).items as unknown[];',
  '      const s = items.filter((x) => typeof x === "string").map((x) => String(x).trim()).filter(Boolean);',
  '      if (s.length > 0) return s;',
  '    }',
  '  }',
  '  return [];',
  '}',
  '',
  'function fmt(n?: number): string {',
  '  return typeof n === "number" ? String(n) : "—";',
  '}',
  '',
  'export default function HomeV2(props: Props) {',
  '  const slug = props.slug;',
  '  const title = props.title;',
  '  const panorama = props.panorama;',
  '  const counts = props.counts || {};',
  '',
  '  const base = "/c/" + slug + "/v2";',
  '  const subtitle = pickFirstString(panorama);',
  '  const fios = pickFios(panorama).slice(0, 6);',
  '',
  '  return (',
  '    <section style={{ display: "flex", flexDirection: "column", gap: 12 }}>',
  '      <header style={{ display: "flex", flexDirection: "column", gap: 6 }}>',
  '        <div style={{ fontSize: 12, opacity: 0.75 }}>Concreto Zen • UI V2</div>',
  '        <h1 style={{ margin: 0, fontSize: 26, letterSpacing: 0.2 }}>{title}</h1>',
  '        {subtitle ? (',
  '          <p style={{ margin: 0, opacity: 0.85, lineHeight: 1.5 }}>{subtitle}</p>',
  '        ) : null}',
  '      </header>',
  '',
  '      <div style={{',
  '        display: "grid",',
  '        gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",',
  '        gap: 12',
  '      }}>',
  '        <Link href={base + "/mapa"} style={{',
  '          textDecoration: "none",',
  '          color: "inherit",',
  '          border: "1px solid rgba(255,255,255,0.10)",',
  '          borderRadius: 14,',
  '          padding: 14,',
  '          background: "rgba(0,0,0,0.35)"',
  '        }}>',
  '          <div style={{ fontSize: 12, opacity: 0.75 }}>Porta 1</div>',
  '          <div style={{ fontSize: 18, marginTop: 4 }}>Mapa</div>',
  '          <div style={{ marginTop: 8, opacity: 0.85, lineHeight: 1.45 }}>',
  '            Território vivo: nós, conexões e camadas.',
  '          </div>',
  '          <div style={{ marginTop: 10, display: "flex", gap: 10, opacity: 0.75, fontSize: 12 }}>',
  '            <span>nós: {fmt(counts.nodes)}</span>',
  '            <span>ligações: {fmt(counts.edges)}</span>',
  '          </div>',
  '        </Link>',
  '',
  '        <Link href={base + "/debate"} style={{',
  '          textDecoration: "none",',
  '          color: "inherit",',
  '          border: "1px solid rgba(255,255,255,0.10)",',
  '          borderRadius: 14,',
  '          padding: 14,',
  '          background: "rgba(0,0,0,0.35)"',
  '        }}>',
  '          <div style={{ fontSize: 12, opacity: 0.75 }}>Porta 2</div>',
  '          <div style={{ fontSize: 18, marginTop: 4 }}>Debate</div>',
  '          <div style={{ marginTop: 8, opacity: 0.85, lineHeight: 1.45 }}>',
  '            Conversas em camadas: tese, perguntas e fricções.',
  '          </div>',
  '          <div style={{ marginTop: 10, display: "flex", gap: 10, opacity: 0.75, fontSize: 12 }}>',
  '            <span>tópicos: {fmt(counts.threads)}</span>',
  '          </div>',
  '        </Link>',
  '',
  '        <Link href={base + "/provas"} style={{',
  '          textDecoration: "none",',
  '          color: "inherit",',
  '          border: "1px solid rgba(255,255,255,0.10)",',
  '          borderRadius: 14,',
  '          padding: 14,',
  '          background: "rgba(0,0,0,0.35)"',
  '        }}>',
  '          <div style={{ fontSize: 12, opacity: 0.75 }}>Porta 3</div>',
  '          <div style={{ fontSize: 18, marginTop: 4 }}>Provas</div>',
  '          <div style={{ marginTop: 8, opacity: 0.85, lineHeight: 1.45 }}>',
  '            Acervo e evidências: documentos, links, trechos e prints.',
  '          </div>',
  '          <div style={{ marginTop: 10, display: "flex", gap: 10, opacity: 0.75, fontSize: 12 }}>',
  '            <span>itens: {fmt(counts.provas)}</span>',
  '          </div>',
  '        </Link>',
  '      </div>',
  '',
  '      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", opacity: 0.9 }}>',
  '        <Link href={base + "/trilhas"} style={{ textDecoration: "underline", color: "inherit" }}>Trilhas</Link>',
  '        <Link href={base + "/linha-do-tempo"} style={{ textDecoration: "underline", color: "inherit" }}>Linha do tempo</Link>',
  '      </div>',
  '',
  '      {fios.length > 0 ? (',
  '        <div style={{',
  '          border: "1px solid rgba(255,255,255,0.10)",',
  '          borderRadius: 14,',
  '          padding: 14,',
  '          background: "rgba(0,0,0,0.25)"',
  '        }}>',
  '          <div style={{ fontSize: 12, opacity: 0.75, marginBottom: 8 }}>Fios quentes</div>',
  '          <ul style={{ margin: 0, paddingLeft: 18, lineHeight: 1.6 }}>',
  '            {fios.map((t) => <li key={t}>{t}</li>)}',
  '          </ul>',
  '        </div>',
  '      ) : null}',
  '    </section>',
  '  );',
  '}'
)
WriteLinesUtf8NoBom $homeCompPath $homeLines
Write-Host ("[OK] wrote: " + $homeCompPath)
if ($bkHome) { Write-Host ("[BK] " + $bkHome) }

# --- 3) /v2 page (server) sem any ---
$bkPage = BackupFile $v2HomePagePath
$pageLines = @(
  'import V2Nav from "@/components/v2/V2Nav";',
  'import HomeV2 from "@/components/v2/HomeV2";',
  'import { loadCadernoV2 } from "@/lib/v2";',
  'import type { JsonValue } from "@/lib/v2/types";',
  '',
  'type PageProps = {',
  '  params: { slug: string };',
  '};',
  '',
  'function isObj(v: unknown): v is Record<string, unknown> {',
  '  return !!v && typeof v === "object" && !Array.isArray(v);',
  '}',
  '',
  'function getJson(v: unknown): JsonValue | null {',
  '  return (v as JsonValue) ?? null;',
  '}',
  '',
  'function pickTitle(data: unknown, slug: string): string {',
  '  if (!isObj(data)) return slug;',
  '  const meta = data["meta"];',
  '  if (isObj(meta) && typeof meta["title"] === "string" && String(meta["title"]).trim().length > 0) {',
  '    return String(meta["title"]);',
  '  }',
  '  if (typeof data["title"] === "string" && String(data["title"]).trim().length > 0) {',
  '    return String(data["title"]);',
  '  }',
  '  return slug;',
  '}',
  '',
  'function countArrFromJson(v: JsonValue | null, keys: string[]): number | undefined {',
  '  if (!v || typeof v !== "object" || Array.isArray(v)) return undefined;',
  '  const o = v as Record<string, JsonValue>;',
  '  for (const k of keys) {',
  '    const x = o[k];',
  '    if (Array.isArray(x)) return x.length;',
  '  }',
  '  return undefined;',
  '}',
  '',
  'export default async function Page(props: PageProps) {',
  '  const slug = props.params.slug;',
  '  const data = await loadCadernoV2(slug);',
  '  const title = pickTitle(data, slug);',
  '',
  '  const d = isObj(data) ? data : {};',
  '  const panorama = ("panorama" in d) ? getJson(d["panorama"]) : null;',
  '  const mapa = ("mapa" in d) ? getJson(d["mapa"]) : null;',
  '  const debate = ("debate" in d) ? getJson(d["debate"]) : null;',
  '  const provas = ("acervo" in d) ? getJson(d["acervo"]) : (("provas" in d) ? getJson(d["provas"]) : null);',
  '  const trilhas = ("trilhas" in d) ? getJson(d["trilhas"]) : null;',
  '',
  '  const counts = {',
  '    nodes: countArrFromJson(mapa, ["nodes", "pontos", "points"]),',
  '    edges: countArrFromJson(mapa, ["edges", "links", "conexoes", "conexões"]),',
  '    threads: countArrFromJson(debate, ["threads", "topicos", "tópicos", "items"]),',
  '    provas: countArrFromJson(provas, ["items", "provas", "evidencias", "evidências", "docs"]),',
  '    trilhas: countArrFromJson(trilhas, ["items", "trilhas", "tracks"])',
  '  };',
  '',
  '  return (',
  '    <main style={{ display: "flex", flexDirection: "column", gap: 12, padding: 14 }}>',
  '      <V2Nav slug={slug} active="home" />',
  '      <HomeV2 slug={slug} title={title} panorama={panorama} counts={counts} />',
  '    </main>',
  '  );',
  '}'
)
WriteLinesUtf8NoBom $v2HomePagePath $pageLines
Write-Host ("[OK] wrote: " + $v2HomePagePath)
if ($bkPage) { Write-Host ("[BK] " + $bkPage) }

# --- VERIFY ---
$verify = Join-Path $repo "tools\cv-verify.ps1"
if (-not (Test-Path -LiteralPath $verify)) { throw ("[STOP] Não achei: " + $verify) }
Write-Host ("[RUN] " + $verify)
& $verify

# --- REPORT ---
$report = @(
  "# CV — Hotfix v0_28 — HomeV2 sem any + V2Nav robusto",
  "",
  "## Fix",
  "- Removeu no-explicit-any em:",
  "  - src/app/c/[slug]/v2/page.tsx",
  "  - src/components/v2/HomeV2.tsx",
  "- Reescreveu V2Nav com active opcional e links consistentes (sem backslash / sem regex-href).",
  "",
  "## Verify",
  "- tools/cv-verify.ps1 (Guard → Lint → Build)",
  ""
) -join "`n"

WriteReport "cv-v2-hotfix-homev2-no-any-v0_28.md" $report | Out-Null
Write-Host "[OK] v0_28 aplicado e verificado."