# CV — V2 Tijolo D2 — Mapa V2 HUD Concreto Zen (canvas + dock + search + hash focus) — v0_40
# DIAG → PATCH → VERIFY → REPORT
$ErrorActionPreference = "Stop"

$toolsDir = if ($PSScriptRoot -and (Test-Path -LiteralPath $PSScriptRoot)) { $PSScriptRoot } else { Join-Path (Get-Location) "tools" }
$repo = (Resolve-Path (Join-Path $toolsDir "..")).Path
. (Join-Path $toolsDir "_bootstrap.ps1")

Write-Host ("[DIAG] Repo: " + $repo)

function WriteFileUtf8([string]$p, [string[]]$lines) {
  EnsureDir (Split-Path -Parent $p)
  $bk = BackupFile $p
  WriteUtf8NoBom $p ($lines -join "`n")
  Write-Host ("[OK] wrote: " + $p)
  if ($bk) { Write-Host ("[BK] " + $bk) }
}

function PatchFile([string]$p, [scriptblock]$fn) {
  if (-not (Test-Path -LiteralPath $p)) { Write-Host ("[SKIP] missing: " + $p); return $false }
  $raw = Get-Content -LiteralPath $p -Raw
  if (-not $raw) { throw ("[STOP] arquivo vazio/ilegivel: " + $p) }
  $next = & $fn $raw
  if ($null -eq $next) { Write-Host ("[SKIP] no-op: " + $p); return $false }
  if ($next -eq $raw) { Write-Host ("[OK] no change: " + $p); return $false }
  $bk = BackupFile $p
  WriteUtf8NoBom $p $next
  Write-Host ("[OK] patched: " + $p)
  if ($bk) { Write-Host ("[BK] " + $bk) }
  return $true
}

# ------------------------------------------------------------
# 1) Client: MapaCanvasV2
# ------------------------------------------------------------
$canvasPath = Join-Path $repo "src\components\v2\MapaCanvasV2.tsx"
$canvasLines = @(
  '"use client";',
  '',
  'import React, { useEffect, useMemo, useState } from "react";',
  '',
  'type NodeItem = {',
  '  id: string;',
  '  title: string;',
  '  kind?: string;',
  '  tags?: string[];',
  '  x?: number;',
  '  y?: number;',
  '};',
  '',
  'function isRecord(v: unknown): v is Record<string, unknown> {',
  '  return typeof v === "object" && v !== null;',
  '}',
  '',
  'function asString(v: unknown): string | undefined {',
  '  return typeof v === "string" ? v : undefined;',
  '}',
  '',
  'function asNumber(v: unknown): number | undefined {',
  '  return typeof v === "number" && Number.isFinite(v) ? v : undefined;',
  '}',
  '',
  'function asStringArray(v: unknown): string[] | undefined {',
  '  if (!Array.isArray(v)) return undefined;',
  '  const out: string[] = [];',
  '  for (const x of v) if (typeof x === "string") out.push(x);',
  '  return out.length ? out : undefined;',
  '}',
  '',
  'function pickArray(obj: Record<string, unknown>, keys: string[]): unknown[] | undefined {',
  '  for (const k of keys) {',
  '    const v = obj[k];',
  '    if (Array.isArray(v)) return v as unknown[];',
  '  }',
  '  return undefined;',
  '}',
  '',
  'function pickString(obj: Record<string, unknown>, keys: string[]): string | undefined {',
  '  for (const k of keys) {',
  '    const s = asString(obj[k]);',
  '    if (s && s.trim()) return s;',
  '  }',
  '  return undefined;',
  '}',
  '',
  'function safeIdFrom(title: string, i: number): string {',
  '  const base = title.toLowerCase().trim()',
  '    .replace(/[^a-z0-9\\s_-]+/g, "")',
  '    .replace(/\\s+/g, "-")',
  '    .slice(0, 48);',
  '  return (base ? base : "no") + "-" + String(i + 1);',
  '}',
  '',
  'function normalizeNodes(input: unknown): NodeItem[] {',
  '  let arr: unknown[] | undefined;',
  '  if (Array.isArray(input)) {',
  '    arr = input;',
  '  } else if (isRecord(input)) {',
  '    arr = pickArray(input, ["nodes","items","list","entries","mapa","mindmap"]);',
  '    if (!arr) {',
  '      const m = input["mapa"];',
  '      if (Array.isArray(m)) arr = m as unknown[];',
  '      if (!arr && isRecord(m)) arr = pickArray(m, ["nodes","items","list","entries"]);',
  '    }',
  '  }',
  '  if (!arr) return [];',
  '',
  '  const out: NodeItem[] = [];',
  '  for (let i = 0; i < arr.length; i++) {',
  '    const it = arr[i];',
  '    if (!isRecord(it)) continue;',
  '    const title = pickString(it, ["title","titulo","name","nome","label"]) ?? ("No " + String(i + 1));',
  '    const id = pickString(it, ["id","slug","key"]) ?? safeIdFrom(title, i);',
  '    const kind = pickString(it, ["kind","type","tipo"]);',
  '    const tags = asStringArray(it["tags"]) ?? asStringArray(it["tag"]);',
  '    const x = asNumber(it["x"]) ?? asNumber(it["px"]) ?? asNumber(it["posX"]);',
  '    const y = asNumber(it["y"]) ?? asNumber(it["py"]) ?? asNumber(it["posY"]);',
  '    out.push({ id, title, kind, tags, x, y });',
  '  }',
  '  return out;',
  '}',
  '',
  'function clamp(n: number, a: number, b: number) {',
  '  return Math.max(a, Math.min(b, n));',
  '}',
  '',
  'function readHashId(): string {',
  '  if (typeof window === "undefined") return "";',
  '  const h = window.location.hash || "";',
  '  return h.startsWith("#") ? h.slice(1) : h;',
  '}',
  '',
  'export default function MapaCanvasV2(props: { mapa: unknown }) {',
  '  const nodes = useMemo(() => normalizeNodes(props.mapa), [props.mapa]);',
  '  const [selectedId, setSelectedId] = useState<string>("");',
  '',
  '  useEffect(() => {',
  '    const onHash = () => setSelectedId(readHashId());',
  '    window.addEventListener("hashchange", onHash);',
  '    const t = setTimeout(onHash, 0);',
  '    const onSel = (ev: Event) => {',
  '      const ce = ev as CustomEvent<{ id?: string }>;',
  '      const id = ce.detail?.id;',
  '      if (id) setSelectedId(id);',
  '    };',
  '    window.addEventListener("cv:mapa-select", onSel as unknown as EventListener);',
  '    return () => {',
  '      clearTimeout(t);',
  '      window.removeEventListener("hashchange", onHash);',
  '      window.removeEventListener("cv:mapa-select", onSel as unknown as EventListener);',
  '    };',
  '  }, []);',
  '',
  '  const hasCoords = useMemo(() => {',
  '    if (!nodes.length) return false;',
  '    let ok = 0;',
  '    for (const n of nodes) if (typeof n.x === "number" && typeof n.y === "number") ok++;',
  '    return ok >= Math.ceil(nodes.length / 2);',
  '  }, [nodes]);',
  '',
  '  function posFor(i: number, n: NodeItem) {',
  '    if (hasCoords && typeof n.x === "number" && typeof n.y === "number") {',
  '      const x = (n.x >= 0 && n.x <= 1) ? n.x : (Math.abs(n.x) % 100) / 100;',
  '      const y = (n.y >= 0 && n.y <= 1) ? n.y : (Math.abs(n.y) % 100) / 100;',
  '      return { left: (clamp(x, 0.05, 0.95) * 100) + "%", top: (clamp(y, 0.08, 0.92) * 100) + "%" };',
  '    }',
  '    const angle = i * 1.7;',
  '    const r = clamp(0.14 + i * 0.02, 0.14, 0.43);',
  '    const x = 0.5 + r * Math.cos(angle);',
  '    const y = 0.5 + r * Math.sin(angle);',
  '    return { left: (clamp(x, 0.06, 0.94) * 100) + "%", top: (clamp(y, 0.10, 0.90) * 100) + "%" };',
  '  }',
  '',
  '  function select(id: string) {',
  '    try {',
  '      window.location.hash = id;',
  '    } catch {',
  '      // noop',
  '    }',
  '    try {',
  '      window.dispatchEvent(new CustomEvent("cv:mapa-select", { detail: { id } }));',
  '    } catch {',
  '      // noop',
  '    }',
  '  }',
  '',
  '  return (',
  '    <div style={{',
  '      position: "relative",',
  '      minHeight: 520,',
  '      borderRadius: 16,',
  '      border: "1px solid rgba(255,255,255,0.10)",',
  '      background: "linear-gradient(180deg, rgba(0,0,0,0.22), rgba(0,0,0,0.35))",',
  '      overflow: "hidden",',
  '    }}>',
  '      <div style={{',
  '        position: "absolute", inset: 0,',
  '        backgroundImage: "radial-gradient(rgba(255,255,255,0.06) 1px, transparent 1px)",',
  '        backgroundSize: "22px 22px",',
  '        opacity: 0.35,',
  '        pointerEvents: "none",',
  '      }} />',
  '',
  '      <div style={{ position: "absolute", left: 12, top: 12, zIndex: 2, display: "flex", gap: 8, flexWrap: "wrap" }}>',
  '        <span style={{ fontSize: 12, opacity: 0.8, padding: "4px 10px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(0,0,0,0.25)" }}>',
  '          mapa vivo',
  '        </span>',
  '        <span style={{ fontSize: 12, opacity: 0.8, padding: "4px 10px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(0,0,0,0.25)" }}>',
  '          clique em um no para focar',
  '        </span>',
  '      </div>',
  '',
  '      {nodes.map((n, i) => {',
  '        const pos = posFor(i, n);',
  '        const on = selectedId === n.id;',
  '        return (',
  '          <button',
  '            key={n.id + "-" + String(i)}',
  '            type="button"',
  '            onClick={() => select(n.id)}',
  '            style={{',
  '              position: "absolute",',
  '              transform: "translate(-50%, -50%)",',
  '              left: pos.left,',
  '              top: pos.top,',
  '              zIndex: on ? 3 : 2,',
  '              maxWidth: 220,',
  '              textAlign: "left",',
  '              borderRadius: 999,',
  '              padding: "10px 12px",',
  '              border: on ? "1px solid rgba(255,215,0,0.55)" : "1px solid rgba(255,255,255,0.14)",',
  '              background: on ? "rgba(255,215,0,0.10)" : "rgba(0,0,0,0.22)",',
  '              color: "white",',
  '              cursor: "pointer",',
  '              boxShadow: on ? "0 0 0 2px rgba(0,0,0,0.25)" : "none",',
  '            }}',
  '            aria-label={"No: " + n.title}',
  '          >',
  '            <div style={{ fontWeight: 800, fontSize: 13, lineHeight: 1.15 }}>',
  '              {n.title}',
  '            </div>',
  '            <div style={{ opacity: 0.72, fontSize: 11, marginTop: 2 }}>',
  '              {(n.kind ? n.kind : "ideia") + (n.tags?.length ? " • " + n.tags.slice(0,2).join(", ") : "")}',
  '            </div>',
  '          </button>',
  '        );',
  '      })}',
  '',
  '      {!nodes.length ? (',
  '        <div style={{ position: "absolute", inset: 0, display: "grid", placeItems: "center", opacity: 0.75, padding: 18 }}>',
  '          Nenhum no encontrado no mapa deste caderno.',
  '        </div>',
  '      ) : null}',
  '    </div>',
  '  );',
  '}'
)
WriteFileUtf8 $canvasPath $canvasLines

# ------------------------------------------------------------
# 2) Client: MapaDockV2 (HUD + busca + lista + copiar link)
# ------------------------------------------------------------
$dockPath = Join-Path $repo "src\components\v2\MapaDockV2.tsx"
$dockLines = @(
  '"use client";',
  '',
  'import Link from "next/link";',
  'import React, { useEffect, useMemo, useState } from "react";',
  '',
  'type NodeItem = { id: string; title: string; kind?: string; tags?: string[]; text?: string };',
  '',
  'function isRecord(v: unknown): v is Record<string, unknown> { return typeof v === "object" && v !== null; }',
  'function asString(v: unknown): string | undefined { return typeof v === "string" ? v : undefined; }',
  'function asStringArray(v: unknown): string[] | undefined {',
  '  if (!Array.isArray(v)) return undefined;',
  '  const out: string[] = [];',
  '  for (const x of v) if (typeof x === "string") out.push(x);',
  '  return out.length ? out : undefined;',
  '}',
  'function pickArray(obj: Record<string, unknown>, keys: string[]): unknown[] | undefined {',
  '  for (const k of keys) { const v = obj[k]; if (Array.isArray(v)) return v as unknown[]; }',
  '  return undefined;',
  '}',
  'function pickString(obj: Record<string, unknown>, keys: string[]): string | undefined {',
  '  for (const k of keys) { const s = asString(obj[k]); if (s && s.trim()) return s; }',
  '  return undefined;',
  '}',
  'function safeIdFrom(title: string, i: number): string {',
  '  const base = title.toLowerCase().trim().replace(/[^a-z0-9\\s_-]+/g, "").replace(/\\s+/g, "-").slice(0, 48);',
  '  return (base ? base : "no") + "-" + String(i + 1);',
  '}',
  'function normalizeNodes(input: unknown): NodeItem[] {',
  '  let arr: unknown[] | undefined;',
  '  if (Array.isArray(input)) arr = input;',
  '  else if (isRecord(input)) {',
  '    arr = pickArray(input, ["nodes","items","list","entries","mapa","mindmap"]);',
  '    if (!arr) {',
  '      const m = input["mapa"];',
  '      if (Array.isArray(m)) arr = m as unknown[];',
  '      if (!arr && isRecord(m)) arr = pickArray(m, ["nodes","items","list","entries"]);',
  '    }',
  '  }',
  '  if (!arr) return [];',
  '  const out: NodeItem[] = [];',
  '  for (let i = 0; i < arr.length; i++) {',
  '    const it = arr[i];',
  '    if (!isRecord(it)) continue;',
  '    const title = pickString(it, ["title","titulo","name","nome","label"]) ?? ("No " + String(i + 1));',
  '    const id = pickString(it, ["id","slug","key"]) ?? safeIdFrom(title, i);',
  '    const kind = pickString(it, ["kind","type","tipo"]);',
  '    const tags = asStringArray(it["tags"]) ?? asStringArray(it["tag"]);',
  '    const text = pickString(it, ["text","texto","desc","descricao","description","notes","nota"]);',
  '    out.push({ id, title, kind, tags, text });',
  '  }',
  '  return out;',
  '}',
  'function readHashId(): string {',
  '  if (typeof window === "undefined") return "";',
  '  const h = window.location.hash || "";',
  '  return h.startsWith("#") ? h.slice(1) : h;',
  '}',
  '',
  'export default function MapaDockV2(props: { slug: string; mapa: unknown }) {',
  '  const nodes = useMemo(() => normalizeNodes(props.mapa), [props.mapa]);',
  '  const [q, setQ] = useState<string>("");',
  '  const [selectedId, setSelectedId] = useState<string>("");',
  '  const [copied, setCopied] = useState<string>("");',
  '',
  '  useEffect(() => {',
  '    const onHash = () => setSelectedId(readHashId());',
  '    window.addEventListener("hashchange", onHash);',
  '    const t = setTimeout(onHash, 0);',
  '    const onSel = (ev: Event) => {',
  '      const ce = ev as CustomEvent<{ id?: string }>;',
  '      const id = ce.detail?.id;',
  '      if (id) setSelectedId(id);',
  '    };',
  '    window.addEventListener("cv:mapa-select", onSel as unknown as EventListener);',
  '    return () => {',
  '      clearTimeout(t);',
  '      window.removeEventListener("hashchange", onHash);',
  '      window.removeEventListener("cv:mapa-select", onSel as unknown as EventListener);',
  '    };',
  '  }, []);',
  '',
  '  const filtered = useMemo(() => {',
  '    const qq = q.trim().toLowerCase();',
  '    if (!qq) return nodes;',
  '    return nodes.filter((n) => {',
  '      const hay = (n.title + " " + (n.kind ?? "") + " " + (n.text ?? "") + " " + (n.tags?.join(" ") ?? "")).toLowerCase();',
  '      return hay.includes(qq);',
  '    });',
  '  }, [nodes, q]);',
  '',
  '  const selected = useMemo(() => filtered.find((n) => n.id === selectedId) ?? nodes.find((n) => n.id === selectedId), [filtered, nodes, selectedId]);',
  '',
  '  async function copyLink(id: string) {',
  '    try {',
  '      const url = window.location.origin + "/c/" + props.slug + "/v2/mapa#" + id;',
  '      await navigator.clipboard.writeText(url);',
  '      setCopied(id);',
  '      setTimeout(() => setCopied(""), 1200);',
  '    } catch {',
  '      // noop',
  '    }',
  '  }',
  '',
  '  return (',
  '    <aside style={{',
  '      border: "1px solid rgba(255,255,255,0.10)",',
  '      borderRadius: 16,',
  '      background: "rgba(0,0,0,0.22)",',
  '      padding: 12,',
  '    }}>',
  '      <div style={{ display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap", alignItems: "baseline" }}>',
  '        <div>',
  '          <div style={{ fontWeight: 900, letterSpacing: 0.4 }}>HUD</div>',
  '          <div style={{ opacity: 0.72, fontSize: 12 }}>Mapa • {nodes.length} nos</div>',
  '        </div>',
  '        <nav style={{ display: "flex", gap: 10, flexWrap: "wrap", opacity: 0.9 }}>',
  '          <Link href={"/c/" + props.slug + "/v2/provas"} style={{ textDecoration: "underline" }}>Provas</Link>',
  '          <Link href={"/c/" + props.slug + "/v2/debate"} style={{ textDecoration: "underline" }}>Debate</Link>',
  '          <Link href={"/c/" + props.slug + "/v2/linha"} style={{ textDecoration: "underline" }}>Linha</Link>',
  '          <Link href={"/c/" + props.slug + "/v2/trilhas"} style={{ textDecoration: "underline" }}>Trilhas</Link>',
  '        </nav>',
  '      </div>',
  '',
  '      <div style={{ marginTop: 10, display: "flex", gap: 10, alignItems: "center", flexWrap: "wrap" }}>',
  '        <input',
  '          value={q}',
  '          onChange={(e) => setQ(e.target.value)}',
  '          placeholder="Buscar no mapa..."',
  '          style={{ flex: "1 1 220px", padding: 10, borderRadius: 12, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(0,0,0,0.25)", color: "white" }}',
  '        />',
  '        <div style={{ opacity: 0.75, fontSize: 12 }}>{filtered.length} resultado(s)</div>',
  '      </div>',
  '',
  '      {selected ? (',
  '        <div style={{ marginTop: 10, padding: 10, borderRadius: 14, border: "1px solid rgba(255,255,255,0.10)", background: "rgba(255,215,0,0.06)" }}>',
  '          <div style={{ display: "flex", justifyContent: "space-between", gap: 10, flexWrap: "wrap" }}>',
  '            <div style={{ minWidth: 200 }}>',
  '              <div style={{ fontWeight: 900 }}>{selected.title}</div>',
  '              <div style={{ opacity: 0.75, fontSize: 12, marginTop: 2 }}>{(selected.kind ?? "ideia") + (selected.tags?.length ? " • " + selected.tags.join(", ") : "")}</div>',
  '            </div>',
  '            <div style={{ display: "flex", gap: 8, alignItems: "center", flexWrap: "wrap" }}>',
  '              <a href={"#" + selected.id} style={{ textDecoration: "underline" }}>Focar</a>',
  '              <button type="button" onClick={() => copyLink(selected.id)} style={{ padding: "8px 10px", borderRadius: 10, border: "1px solid rgba(255,255,255,0.18)", background: "rgba(0,0,0,0.25)", color: "white", cursor: "pointer" }}>',
  '                {copied === selected.id ? "Copiado!" : "Copiar link"}',
  '              </button>',
  '            </div>',
  '          </div>',
  '          {selected.text ? (',
  '            <div style={{ marginTop: 8, opacity: 0.9, lineHeight: 1.35, fontSize: 13 }}>{selected.text}</div>',
  '          ) : null}',
  '        </div>',
  '      ) : null}',
  '',
  '      <div style={{ marginTop: 10, maxHeight: 320, overflow: "auto", borderTop: "1px solid rgba(255,255,255,0.08)", paddingTop: 10 }}>',
  '        {filtered.map((n, i) => {',
  '          const on = n.id === selectedId;',
  '          return (',
  '            <a',
  '              key={n.id + "-" + String(i)}',
  '              href={"#" + n.id}',
  '              style={{',
  '                display: "block",',
  '                padding: "9px 10px",',
  '                borderRadius: 12,',
  '                marginBottom: 6,',
  '                textDecoration: "none",',
  '                color: "white",',
  '                border: on ? "1px solid rgba(255,215,0,0.45)" : "1px solid rgba(255,255,255,0.10)",',
  '                background: on ? "rgba(255,215,0,0.08)" : "rgba(0,0,0,0.18)",',
  '              }}',
  '            >',
  '              <div style={{ fontWeight: 800, fontSize: 13 }}>{n.title}</div>',
  '              <div style={{ opacity: 0.72, fontSize: 12, marginTop: 2 }}>{(n.kind ?? "ideia")}</div>',
  '            </a>',
  '          );',
  '        })}',
  '        {!filtered.length ? (',
  '          <div style={{ opacity: 0.75, padding: 10, borderRadius: 12, border: "1px dashed rgba(255,255,255,0.18)" }}>Nada encontrado.</div>',
  '        ) : null}',
  '      </div>',
  '    </aside>',
  '  );',
  '}'
)
WriteFileUtf8 $dockPath $dockLines

# ------------------------------------------------------------
# 3) Server: MapaV2 (shell Concreto Zen)
# ------------------------------------------------------------
$mapaV2Path = Join-Path $repo "src\components\v2\MapaV2.tsx"
$mapaLines = @(
  'import React from "react";',
  'import MapaCanvasV2 from "@/components/v2/MapaCanvasV2";',
  'import MapaDockV2 from "@/components/v2/MapaDockV2";',
  '',
  'export default function MapaV2(props: { slug: string; title?: string; mapa: unknown }) {',
  '  const title = props.title ?? props.slug;',
  '  const mapa = props.mapa;',
  '',
  '  return (',
  '    <section style={{ marginTop: 12 }}>',
  '      <header style={{ display: "flex", justifyContent: "space-between", gap: 12, alignItems: "flex-end", flexWrap: "wrap" }}>',
  '        <div>',
  '          <h1 style={{ margin: 0, fontSize: 22, letterSpacing: 0.2 }}>Mapa</h1>',
  '          <div style={{ opacity: 0.75, marginTop: 2 }}>{title} • Concreto Zen</div>',
  '        </div>',
  '        <div style={{ opacity: 0.8, fontSize: 12 }}>',
  '          dica: use o hash (#id) para linkar um no especifico',
  '        </div>',
  '      </header>',
  '',
  '      <div style={{ marginTop: 12, display: "grid", gap: 12, gridTemplateColumns: "1.7fr 1fr", alignItems: "start" }}>',
  '        <MapaCanvasV2 mapa={mapa} />',
  '        <MapaDockV2 slug={props.slug} mapa={mapa} />',
  '      </div>',
  '    </section>',
  '  );',
  '}'
)
WriteFileUtf8 $mapaV2Path $mapaLines

# ------------------------------------------------------------
# 4) Page: /v2/mapa (await params + carrega meta/mapa)
# ------------------------------------------------------------
$pagePath = Join-Path $repo "src\app\c\[slug]\v2\mapa\page.tsx"
if (Test-Path -LiteralPath $pagePath) {
  $bk = BackupFile $pagePath
}

$pageLines = @(
  'import V2Nav from "@/components/v2/V2Nav";',
  'import MapaV2 from "@/components/v2/MapaV2";',
  'import { loadCadernoV2 } from "@/lib/v2";',
  '',
  'function titleFromMeta(meta: unknown, fallback: string): string {',
  '  if (typeof meta !== "object" || meta === null) return fallback;',
  '  const r = meta as { title?: unknown };',
  '  return typeof r.title === "string" && r.title.trim() ? r.title : fallback;',
  '}',
  '',
  'export default async function Page(props: { params: Promise<{ slug: string }> }) {',
  '  const slug = (await props.params).slug;',
  '  const c = await loadCadernoV2(slug);',
  '',
  '  const meta = (c as unknown as { meta?: unknown }).meta;',
  '  const title = titleFromMeta(meta, slug);',
  '  const bag = c as unknown as { mapa?: unknown; map?: unknown; mindmap?: unknown };',
  '  const mapa = bag.mapa ?? bag.map ?? bag.mindmap ?? null;',
  '',
  '  return (',
  '    <main style={{ padding: 18 }}>',
  '      <V2Nav slug={slug} active="mapa" />',
  '      <MapaV2 slug={slug} title={title} mapa={mapa} />',
  '    </main>',
  '  );',
  '}'
)
WriteFileUtf8 $pagePath $pageLines
if ($bk) { Write-Host ("[BK] " + $bk) }

# ------------------------------------------------------------
# 5) Safety: garantir V2 pages usando await props.params.slug (best-effort)
# ------------------------------------------------------------
$v2Root = Join-Path $repo "src\app\c\[slug]\v2"
if (Test-Path -LiteralPath $v2Root) {
  $pages = Get-ChildItem -LiteralPath $v2Root -Recurse -File -Filter "page.tsx"
  foreach ($f in $pages) {
    PatchFile $f.FullName {
      param($raw)
      $o = $raw
      if ($o -match 'props:\s*\{\s*params:\s*\{\s*slug:\s*string\s*\}\s*\}') {
        $o = $o -replace 'props:\s*\{\s*params:\s*\{\s*slug:\s*string\s*\}\s*\}', 'props: { params: Promise<{ slug: string }> }'
      }
      if ($o -match 'props\.params\.slug' -and ($o -notmatch '\(await props\.params\)\.slug')) {
        $o = $o.Replace("props.params.slug", "(await props.params).slug")
      }
      return $o
    } | Out-Null
  }
}

# ------------------------------------------------------------
# VERIFY
# ------------------------------------------------------------
RunPs1 (Join-Path $repo "tools\cv-verify.ps1")

# ------------------------------------------------------------
# REPORT
# ------------------------------------------------------------
$rep = @(
  '# CV — V2 Tijolo D2 v0_40 — Mapa HUD Concreto Zen',
  '',
  '## O que entrou',
  '- MapaCanvasV2: canvas de nos (layout deterministico) + selecao por hash e evento cv:mapa-select.',
  '- MapaDockV2: HUD com busca, lista, painel do no selecionado, copiar link com hash.',
  '- MapaV2: shell Concreto Zen (canvas + dock).',
  '- Page /v2/mapa: await params (Next 16.1) + carrega meta e mapa.',
  '',
  '## Arquivos',
  '- src/components/v2/MapaCanvasV2.tsx',
  '- src/components/v2/MapaDockV2.tsx',
  '- src/components/v2/MapaV2.tsx',
  '- src/app/c/[slug]/v2/mapa/page.tsx',
  '',
  '## Verify',
  '- tools/cv-verify.ps1 (guard + lint + build)',
  ''
) -join "`n"

WriteReport "cv-v2-tijolo-d2-mapa-hud-concretozen-v0_40.md" $rep | Out-Null
Write-Host "[OK] D2 v0_40 aplicado e verificado."