# CV — V2 Tijolo D4 — Provas/Acervo V2 + hotfix MapaDockV2 setState-in-effect — v0_36
# DIAG → PATCH → VERIFY → REPORT
$ErrorActionPreference = "Stop"

$repo = Get-Location
$bootstrap = Join-Path $repo "tools\_bootstrap.ps1"
if (-not (Test-Path -LiteralPath $bootstrap)) { throw "[STOP] tools/_bootstrap.ps1 não encontrado." }
. $bootstrap

Write-Host ("[DIAG] Repo: " + $repo)

# Paths
$provasComp = Join-Path $repo "src\components\v2\ProvasV2.tsx"
$provasPage = Join-Path $repo "src\app\c\[slug]\v2\provas\page.tsx"
$dockFile  = Join-Path $repo "src\components\v2\MapaDockV2.tsx"

if (-not (Test-Path -LiteralPath $provasPage)) { throw ("[STOP] Não achei page: " + $provasPage) }
EnsureDir (Split-Path -Parent $provasComp)

Write-Host ("[DIAG] ProvasV2: " + $provasComp)
Write-Host ("[DIAG] Page:    " + $provasPage)

# --- PATCH 0: Hotfix MapaDockV2 (setState-in-effect) ---
if (Test-Path -LiteralPath $dockFile) {
  $dockRaw = Get-Content -LiteralPath $dockFile -Raw
  $dockNew = $dockRaw.Replace("setSelectedId(readHashId());", "setTimeout(() => setSelectedId(readHashId()), 0);")
  if ($dockNew -ne $dockRaw) {
    $bkDock = BackupFile $dockFile
    WriteUtf8NoBom $dockFile $dockNew
    Write-Host "[OK] patched: MapaDockV2.tsx (setState-in-effect -> setTimeout callback)"
    if ($bkDock) { Write-Host ("[BK] " + $bkDock) }
  } else {
    Write-Host "[OK] MapaDockV2: no change (linha alvo não encontrada)."
  }
} else {
  Write-Host "[SKIP] MapaDockV2 não existe — ok."
}

# --- PATCH 1: ProvasV2 component (client) ---
$bk1 = BackupFile $provasComp

$provasLines = @(
'"use client";',
'',
'import React, { useMemo, useState } from "react";',
'import Link from "next/link";',
'',
'type Proof = {',
'  id: string;',
'  title: string;',
'  kind: string;',
'  url: string | null;',
'  nodeId: string | null;',
'  tags: string[];',
'};',
'',
'type Props = {',
'  slug: string;',
'  title: string;',
'  acervo: unknown;',
'};',
'',
'function asRecord(v: unknown): Record<string, unknown> | null {',
'  if (!v || typeof v !== "object") return null;',
'  return v as Record<string, unknown>;',
'}',
'',
'function asArray(v: unknown): unknown[] | null {',
'  return Array.isArray(v) ? v : null;',
'}',
'',
'function asString(v: unknown): string | null {',
'  return typeof v === "string" ? v : null;',
'}',
'',
'function pickId(o: Record<string, unknown>, fallback: string): string {',
'  const a = asString(o["id"]);',
'  if (a) return a;',
'  const b = asString(o["slug"]);',
'  if (b) return b;',
'  const c = asString(o["key"]);',
'  if (c) return c;',
'  const u = asString(o["url"]) || asString(o["href"]) || asString(o["link"]);',
'  if (u) return "u-" + String(u.length) + "-" + fallback;',
'  return fallback;',
'}',
'',
'function pickTitle(o: Record<string, unknown>): string {',
'  const a = asString(o["title"]);',
'  if (a) return a;',
'  const b = asString(o["label"]);',
'  if (b) return b;',
'  const c = asString(o["name"]);',
'  if (c) return c;',
'  const d = asString(o["url"]) || asString(o["href"]) || asString(o["link"]);',
'  if (d) return d;',
'  return "Sem título";',
'}',
'',
'function pickKind(o: Record<string, unknown>): string {',
'  const a = asString(o["type"]);',
'  if (a) return a;',
'  const b = asString(o["kind"]);',
'  if (b) return b;',
'  const c = asString(o["category"]);',
'  if (c) return c;',
'  return "prova";',
'}',
'',
'function pickUrl(o: Record<string, unknown>): string | null {',
'  return asString(o["url"]) || asString(o["href"]) || asString(o["link"]);',
'}',
'',
'function pickNodeId(o: Record<string, unknown>): string | null {',
'  return asString(o["nodeId"]) || asString(o["node"]) || asString(o["mapId"]) || asString(o["anchor"]);',
'}',
'',
'function pickTags(o: Record<string, unknown>): string[] {',
'  const t = o["tags"];',
'  const arr = asArray(t);',
'  if (arr) {',
'    const out: string[] = [];',
'    for (let i = 0; i < arr.length; i++) {',
'      const s = asString(arr[i]);',
'      if (s) out.push(s);',
'    }',
'    return out.slice(0, 12);',
'  }',
'  const one = asString(o["tag"]);',
'  return one ? [one] : [];',
'}',
'',
'function extractProofs(acervo: unknown): Proof[] {',
'  let items: unknown[] = [];',
'  const ao = asArray(acervo);',
'  if (ao) items = ao;',
'  const ro = asRecord(acervo);',
'  if (ro) {',
'    const a = asArray(ro["items"]);',
'    const b = asArray(ro["provas"]);',
'    const c = asArray(ro["links"]);',
'    if (a) items = a;',
'    else if (b) items = b;',
'    else if (c) items = c;',
'  }',
'',
'  const out: Proof[] = [];',
'  for (let i = 0; i < items.length; i++) {',
'    const o = asRecord(items[i]);',
'    if (!o) continue;',
'    const id = pickId(o, "item-" + i);',
'    const title = pickTitle(o);',
'    const kind = pickKind(o);',
'    const url = pickUrl(o);',
'    const nodeId = pickNodeId(o);',
'    const tags = pickTags(o);',
'    out.push({ id, title, kind, url, nodeId, tags });',
'    if (out.length >= 250) break;',
'  }',
'  return out;',
'}',
'',
'function uniqTags(items: Proof[]): string[] {',
'  const set = new Set<string>();',
'  for (let i = 0; i < items.length; i++) {',
'    const t = items[i].tags;',
'    for (let j = 0; j < t.length; j++) set.add(t[j]);',
'  }',
'  return Array.from(set).slice(0, 40);',
'}',
'',
'export default function ProvasV2(props: Props) {',
'  const { slug, title, acervo } = props;',
'',
'  const baseV2 = "/c/" + slug + "/v2";',
'  const all = useMemo(() => extractProofs(acervo), [acervo]);',
'  const tagsAll = useMemo(() => uniqTags(all), [all]);',
'',
'  const [q, setQ] = useState<string>("");',
'  const [kind, setKind] = useState<string>("");',
'  const [tag, setTag] = useState<string>("");',
'',
'  const filtered = useMemo(() => {',
'    const qq = q.trim().toLowerCase();',
'    return all.filter((it) => {',
'      if (kind && it.kind !== kind) return false;',
'      if (tag && !it.tags.includes(tag)) return false;',
'      if (!qq) return true;',
'      const hay = (it.title + " " + it.kind + " " + it.tags.join(" ")).toLowerCase();',
'      return hay.includes(qq);',
'    });',
'  }, [all, q, kind, tag]);',
'',
'  const kinds = useMemo(() => {',
'    const set = new Set<string>();',
'    for (let i = 0; i < all.length; i++) set.add(all[i].kind);',
'    return Array.from(set).slice(0, 20);',
'  }, [all]);',
'',
'  return (',
'    <section style={{ display: "flex", gap: 12, alignItems: "stretch" }}>',
'      <aside',
'        style={{',
'          width: 360,',
'          maxWidth: "42vw",',
'          border: "1px solid rgba(255,255,255,0.08)",',
'          background: "rgba(255,255,255,0.03)",',
'          borderRadius: 14,',
'          padding: 12,',
'          height: "calc(100vh - 110px)",',
'          overflow: "auto",',
'        }}',
'      >',
'        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 10 }}>',
'          <div>',
'            <div style={{ fontSize: 12, opacity: 0.85 }}>Provas / Acervo</div>',
'            <div style={{ fontSize: 18, fontWeight: 900, letterSpacing: 0.2 }}>{title}</div>',
'          </div>',
'          <div style={{ fontSize: 12, opacity: 0.85 }}>{filtered.length} / {all.length}</div>',
'        </div>',
'',
'        <div style={{ height: 10 }} />',
'        <input',
'          value={q}',
'          onChange={(e) => setQ(e.target.value)}',
'          placeholder="Buscar no acervo…" ',
'          style={{',
'            width: "100%",',
'            padding: "10px 12px",',
'            borderRadius: 12,',
'            border: "1px solid rgba(255,255,255,0.10)",',
'            background: "rgba(0,0,0,0.25)",',
'            color: "white",',
'            outline: "none",',
'          }}',
'        />',
'',
'        <div style={{ height: 10 }} />',
'        <div style={{ display: "flex", gap: 10, flexWrap: "wrap", alignItems: "center" }}>',
'          <label style={{ fontSize: 12, opacity: 0.85 }}>Tipo</label>',
'          <select',
'            value={kind}',
'            onChange={(e) => setKind(e.target.value)}',
'            style={{',
'              padding: "8px 10px",',
'              borderRadius: 12,',
'              border: "1px solid rgba(255,255,255,0.10)",',
'              background: "rgba(0,0,0,0.25)",',
'              color: "white",',
'            }}',
'          >',
'            <option value="">Todos</option>',
'            {kinds.map((k) => (',
'              <option key={k} value={k}>{k}</option>',
'            ))}',
'          </select>',
'',
'          <button',
'            onClick={() => { setQ(""); setKind(""); setTag(""); }}',
'            style={{',
'              padding: "8px 10px",',
'              borderRadius: 12,',
'              border: "1px solid rgba(255,255,255,0.10)",',
'              background: "rgba(255,255,255,0.06)",',
'              color: "white",',
'              cursor: "pointer",',
'              fontWeight: 800,',
'            }}',
'          >',
'            Limpar',
'          </button>',
'        </div>',
'',
'        <div style={{ height: 10 }} />',
'        <div style={{ fontSize: 12, opacity: 0.85 }}>Tags</div>',
'        <div style={{ marginTop: 8, display: "flex", gap: 8, flexWrap: "wrap" }}>',
'          {tagsAll.length === 0 ? (',
'            <div style={{ opacity: 0.8, lineHeight: 1.5 }}>Sem tags detectadas.</div>',
'          ) : (',
'            tagsAll.map((t) => (',
'              <button',
'                key={t}',
'                onClick={() => setTag((prev) => (prev === t ? "" : t))}',
'                style={{',
'                  padding: "6px 10px",',
'                  borderRadius: 999,',
'                  border: "1px solid rgba(255,255,255,0.10)",',
'                  background: tag === t ? "rgba(255,255,255,0.10)" : "rgba(0,0,0,0.0)",',
'                  color: "white",',
'                  cursor: "pointer",',
'                  fontSize: 12,',
'                }}',
'              >',
'                {t}',
'              </button>',
'            ))',
'          )}',
'        </div>',
'',
'        <div style={{ height: 14 }} />',
'        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>',
'          <Link href={baseV2} style={{ textDecoration: "underline", opacity: 0.9 }}>Home</Link>',
'          <Link href={baseV2 + "/mapa"} style={{ textDecoration: "underline", opacity: 0.9 }}>Mapa</Link>',
'          <Link href={baseV2 + "/debate"} style={{ textDecoration: "underline", opacity: 0.9 }}>Debate</Link>',
'          <Link href={baseV2 + "/linha"} style={{ textDecoration: "underline", opacity: 0.9 }}>Linha</Link>',
'        </div>',
'      </aside>',
'',
'      <main style={{ flex: 1, minWidth: 0 }}>',
'        <div',
'          style={{',
'            border: "1px solid rgba(255,255,255,0.08)",',
'            background: "rgba(255,255,255,0.03)",',
'            borderRadius: 14,',
'            padding: 14,',
'            minHeight: "calc(100vh - 110px)",',
'          }}',
'        >',
'          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", gap: 10, flexWrap: "wrap" }}>',
'            <div>',
'              <div style={{ fontSize: 12, opacity: 0.85 }}>Lista</div>',
'              <div style={{ fontSize: 20, fontWeight: 900, letterSpacing: 0.2 }}>Acervo</div>',
'            </div>',
'            <button',
'              onClick={async () => {',
'                try {',
'                  const url = (typeof window !== "undefined" ? window.location.origin : "") + (baseV2 + "/provas");',
'                  await navigator.clipboard.writeText(url);',
'                } catch {',
'                  /* noop */',
'                }',
'              }}',
'              style={{',
'                padding: "10px 12px",',
'                borderRadius: 12,',
'                border: "1px solid rgba(255,255,255,0.10)",',
'                background: "rgba(255,255,255,0.06)",',
'                color: "white",',
'                cursor: "pointer",',
'                fontWeight: 800,',
'              }}',
'            >',
'              Copiar link da página',
'            </button>',
'          </div>',
'',
'          <div style={{ height: 12 }} />',
'',
'          {filtered.length === 0 ? (',
'            <div style={{ opacity: 0.85, lineHeight: 1.6 }}>',
'              Nenhum item encontrado com os filtros atuais.',
'            </div>',
'          ) : (',
'            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>',
'              {filtered.map((it) => {',
'                const hrefSelf = baseV2 + "/provas#" + it.id;',
'                const hrefMapa = baseV2 + "/mapa#" + (it.nodeId ? it.nodeId : it.id);',
'                return (',
'                  <div',
'                    key={it.id}',
'                    id={it.id}',
'                    style={{',
'                      border: "1px solid rgba(255,255,255,0.10)",',
'                      background: "rgba(0,0,0,0.20)",',
'                      borderRadius: 14,',
'                      padding: 12,',
'                    }}',
'                  >',
'                    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: 10, flexWrap: "wrap" }}>',
'                      <div style={{ minWidth: 0 }}>',
'                        <div style={{ fontWeight: 900, fontSize: 16, lineHeight: 1.25 }}>{it.title}</div>',
'                        <div style={{ fontSize: 12, opacity: 0.75, marginTop: 4 }}>',
'                          {it.kind} · {it.id}',
'                          {it.nodeId ? (" · node: " + it.nodeId) : ""}',
'                        </div>',
'                      </div>',
'                      <div style={{ display: "flex", gap: 10, flexWrap: "wrap", justifyContent: "flex-end" }}>',
'                        <Link href={hrefSelf} style={{ textDecoration: "underline", opacity: 0.9 }}>#</Link>',
'                        <Link href={hrefMapa} style={{ textDecoration: "underline", opacity: 0.9 }}>Mapa</Link>',
'                        <Link href={baseV2 + "/debate"} style={{ textDecoration: "underline", opacity: 0.9 }}>Debate</Link>',
'                        {it.url ? (',
'                          <a href={it.url} target="_blank" rel="noreferrer" style={{ textDecoration: "underline", opacity: 0.95 }}>Abrir</a>',
'                        ) : null}',
'                        <button',
'                          onClick={async () => {',
'                            try {',
'                              const url = (typeof window !== "undefined" ? window.location.origin : "") + hrefSelf;',
'                              await navigator.clipboard.writeText(url);',
'                            } catch {',
'                              /* noop */',
'                            }',
'                          }}',
'                          style={{',
'                            padding: "8px 10px",',
'                            borderRadius: 12,',
'                            border: "1px solid rgba(255,255,255,0.10)",',
'                            background: "rgba(255,255,255,0.06)",',
'                            color: "white",',
'                            cursor: "pointer",',
'                            fontWeight: 800,',
'                          }}',
'                        >',
'                          Copiar link',
'                        </button>',
'                      </div>',
'                    </div>',
'',
'                    {it.tags.length > 0 ? (',
'                      <div style={{ marginTop: 10, display: "flex", gap: 8, flexWrap: "wrap" }}>',
'                        {it.tags.map((t) => (',
'                          <span',
'                            key={t}',
'                            style={{',
'                              fontSize: 12,',
'                              padding: "4px 8px",',
'                              borderRadius: 999,',
'                              border: "1px solid rgba(255,255,255,0.10)",',
'                              background: "rgba(255,255,255,0.05)",',
'                              opacity: 0.95,',
'                            }}',
'                          >',
'                            {t}',
'                          </span>',
'                        ))}',
'                      </div>',
'                    ) : null}',
'                  </div>',
'                );',
'              })}',
'            </div>',
'          )}',
'        </div>',
'      </main>',
'    </section>',
'  );',
'}'
)

WriteLinesUtf8NoBom $provasComp $provasLines
Write-Host ("[OK] wrote: " + $provasComp)
if ($bk1) { Write-Host ("[BK] " + $bk1) }

# --- PATCH 2: v2/provas/page.tsx (server) ---
$bk2 = BackupFile $provasPage

$pageLines = @(
'import V2Nav from "@/components/v2/V2Nav";',
'import ProvasV2 from "@/components/v2/ProvasV2";',
'import { loadCadernoV2 } from "@/lib/v2";',
'',
'export default async function Page(props: { params: { slug: string } }) {',
'  const slug = props.params.slug;',
'  const c = await loadCadernoV2(slug);',
'',
'  const title = (c.meta && c.meta.title ? c.meta.title : slug);',
'  const acervo = c.acervo;',
'',
'  return (',
'    <main',
'      style={{',
'        minHeight: "100vh",',
'        padding: 16,',
'        background: "#0b0b0c",',
'        color: "white",',
'      }}',
'    >',
'      <V2Nav slug={slug} active="provas" />',
'      <div style={{ height: 12 }} />',
'      <ProvasV2 slug={slug} title={title} acervo={acervo} />',
'    </main>',
'  );',
'}'
)

WriteLinesUtf8NoBom $provasPage $pageLines
Write-Host ("[OK] wrote: " + $provasPage)
if ($bk2) { Write-Host ("[BK] " + $bk2) }

# VERIFY
RunPs1 (Join-Path $repo "tools\cv-verify.ps1") @()

# REPORT
$report = @(
  "# CV — Tijolo D4 v0_36 — Provas/Acervo V2 + hotfix MapaDockV2",
  "",
  "## O que entrou",
  "- src/components/v2/ProvasV2.tsx: lista do acervo com filtros (q, tipo, tag) + cards + copiar link + abrir no mapa/debate.",
  "- src/app/c/[slug]/v2/provas/page.tsx: server page usando loadCadernoV2 + meta.title.",
  "",
  "## Hotfix de lint",
  "- src/components/v2/MapaDockV2.tsx: troca setSelectedId(readHashId()) dentro do useEffect por setTimeout(() => setSelectedId(...), 0).",
  "",
  "## Verify",
  "- tools/cv-verify.ps1 (Guard → Lint → Build)",
  ""
) -join "`n"

WriteReport "cv-v2-tijolo-d4-provas-v2-acervo-v0_36.md" $report | Out-Null
Write-Host "[OK] D4 v0_36 aplicado e verificado."